packages:
  - apps/*
  - packages/*
  - packages/@luke-ui/*

catalog:
  '@argos-ci/storybook': ^5.2.14
  '@storybook/addon-a11y': ^10.2.17
  '@storybook/addon-docs': ^10.2.17
  '@storybook/addon-vitest': ^10.2.17
  '@storybook/react-vite': ^10.2.17
  '@types/node': ^25.5.0
  '@types/react-dom': ^19.2.3
  '@types/react': ^19.2.14
  '@vanilla-extract/vite-plugin': ^5.2.0
  '@vitejs/plugin-react': ^6.0.0
  '@vitest/browser-playwright': ^4.1.0
  '@vitest/coverage-v8': ^4.1.0
  '@vitest/ui': ^4.1.0
  'fumadocs-mdx': ^14.2.10
  'oxlint-tsgolint': ^0.16.0
  'react-dom': ^19.2.4
  'react': ^19.2.4
  'storybook': ^10.2.17
  'tsx': ^4.21.0
  'vite': ^8.0.0
  'vitest': ^4.1.0

overrides:
  undici: ^7.24.3

peerDependencyRules:
  allowedVersions:
    '@tailwindcss/vite>vite': ^8.0.0
    '@joshwooding/vite-plugin-react-docgen-typescript>vite': ^8.0.0

ignoredBuiltDependencies:
  - esbuild
