const SPECIFIER_TO_IDENTIFIER_RE = /^@|[^a-zA-Z0-9]+/g;

export function specifierToIdentifier(specifier: string): string {
	return specifier.replace(SPECIFIER_TO_IDENTIFIER_RE, (match) => (match === '@' ? '' : '_'));
}

/**
 * Renders the TypeScript module that maps playground import specifiers to
 * live namespace imports. Hosts write the result to their generated output path.
 */
export function renderPlaygroundScopeModule(specifiers: ReadonlyArray<string>): string {
	const importLines = specifiers.map(
		(specifier) => `import * as ${specifierToIdentifier(specifier)} from '${specifier}';`,
	);
	const entryLines = specifiers.map(
		(specifier) => `\t'${specifier}': ${specifierToIdentifier(specifier)},`,
	);

	return `// Generated by playground scope generation — do not edit.
${importLines.join('\n')}

export const playgroundScope: Record<string, unknown> = {
${entryLines.join('\n')}
};
`;
}
