import { mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { afterEach, describe, expect, test } from 'vite-plus/test';
import { formatPlaygroundSource } from './format.js';
import {
	createPlaygroundTypeMap,
	playgroundVirtualPath,
	renderPlaygroundScopeModule,
	resolvePackageDir,
	walkPackageFiles,
} from './generate.js';

describe('renderPlaygroundScopeModule', () => {
	test('imports each specifier under a positional identifier', () => {
		expect(renderPlaygroundScopeModule(['react', '@scope/ui/box'])).toBe(
			[
				'// Generated by playground scope generation — do not edit.',
				'import * as module0 from "react";',
				'import * as module1 from "@scope/ui/box";',
				'',
				'export const playgroundScope: Record<string, unknown> = {',
				'\t"react": module0,',
				'\t"@scope/ui/box": module1,',
				'};',
				'',
			].join('\n'),
		);
	});

	test('keeps specifiers distinct that would collapse to the same identifier', async () => {
		const source = renderPlaygroundScopeModule(['foo-bar', 'foo_bar', '3d-engine']);
		expect(source).toContain('import * as module0 from "foo-bar";');
		expect(source).toContain('import * as module1 from "foo_bar";');
		expect(source).toContain('import * as module2 from "3d-engine";');
		await expectValidModule(source);
	});

	test('writes scoped packages and deep subpaths as string literals', async () => {
		const source = renderPlaygroundScopeModule(['@scope/pkg', '@scope/pkg/a/b/c', 'pkg/deep/path']);
		expect(source).toContain('\t"@scope/pkg/a/b/c": module1,');
		expect(source).toContain('\t"pkg/deep/path": module2,');
		await expectValidModule(source);
	});

	test('escapes quotes and backslashes in specifiers', async () => {
		const source = renderPlaygroundScopeModule(['odd"name', 'back\\slash', "it's"]);
		expect(source).toContain('import * as module0 from "odd\\"name";');
		expect(source).toContain('import * as module1 from "back\\\\slash";');
		expect(source).toContain('import * as module2 from "it\'s";');
		await expectValidModule(source);
	});

	test('renders an empty scope for an empty list', async () => {
		const source = renderPlaygroundScopeModule([]);
		expect(source).not.toContain('import');
		expect(source).toContain('export const playgroundScope: Record<string, unknown> = {\n};');
		await expectValidModule(source);
	});

	test('rejects a duplicate specifier', () => {
		expect(() => renderPlaygroundScopeModule(['react', 'zod', 'react'])).toThrow(
			'renderPlaygroundScopeModule: duplicate specifier "react".',
		);
	});
});

describe('playground type map', () => {
	let fixtureDir: string | undefined;

	afterEach(() => {
		if (fixtureDir) rmSync(fixtureDir, { force: true, recursive: true });
		fixtureDir = undefined;
	});

	function createFixture(files: Record<string, string>): string {
		// Resolved so paths match what Node's resolver returns through a symlinked temp dir.
		fixtureDir = realpathSync(mkdtempSync(join(tmpdir(), 'playground-core-generate-')));
		for (const [path, contents] of Object.entries(files)) {
			const filePath = join(fixtureDir, path);
			mkdirSync(dirname(filePath), { recursive: true });
			writeFileSync(filePath, contents);
		}
		return fixtureDir;
	}

	test('builds virtual node_modules paths with forward slashes', () => {
		expect(playgroundVirtualPath('@scope/ui', join('dist', 'box.d.ts'))).toBe(
			'file:///node_modules/@scope/ui/dist/box.d.ts',
		);
	});

	test('adds a package tree of declarations, then its package.json', () => {
		const root = createFixture({
			'pkg/index.d.ts': 'export {};',
			'pkg/index.js': '',
			'pkg/lib/util.d.ts': 'export type A = 1;',
			'pkg/node_modules/nested/index.d.ts': 'export {};',
			'pkg/package.json': '{"name":"pkg"}',
		});
		const typeMap = createPlaygroundTypeMap();
		typeMap.addPackage('pkg', join(root, 'pkg'));

		expect(typeMap.files()).toEqual({
			'file:///node_modules/pkg/index.d.ts': 'export {};',
			'file:///node_modules/pkg/lib/util.d.ts': 'export type A = 1;',
			'file:///node_modules/pkg/package.json': '{"name":"pkg"}',
		});
		expect(Object.keys(typeMap.files()).at(-1)).toBe('file:///node_modules/pkg/package.json');
	});

	test('collects declarations from a subdirectory and writes a package.json stub', () => {
		const root = createFixture({
			'ui/dist/box.d.ts': 'export {};',
			'ui/package.json': '{"name":"@scope/ui","private":true}',
			'ui/src/box.d.ts': 'export {};',
		});
		const typeMap = createPlaygroundTypeMap();
		typeMap.addPackage('@scope/ui', join(root, 'ui'), {
			packageJson: { exports: { './box': './dist/box.js' }, name: '@scope/ui' },
			typesDir: 'dist',
		});
		typeMap.addFile('file:///host/helpers.tsx', 'export const helper = 1;');

		expect(typeMap.files()).toEqual({
			'file:///host/helpers.tsx': 'export const helper = 1;',
			'file:///node_modules/@scope/ui/dist/box.d.ts': 'export {};',
			'file:///node_modules/@scope/ui/package.json':
				'{"exports":{"./box":"./dist/box.js"},"name":"@scope/ui"}',
		});
	});

	test('walks files depth first and skips node_modules', () => {
		const root = createFixture({
			'a/b.txt': '',
			'a/node_modules/c.txt': '',
			'd.txt': '',
		});
		const visited: Array<string> = [];
		walkPackageFiles(root, (filePath) => visited.push(filePath.slice(root.length + 1)));

		expect(visited.sort()).toEqual([join('a', 'b.txt'), 'd.txt']);
	});

	test('resolves a package directory through its package.json export', () => {
		const root = createFixture({
			'app/node_modules/dep/index.js': '',
			'app/node_modules/dep/package.json': '{"name":"dep","main":"index.js"}',
			'app/package.json': '{"name":"app"}',
		});

		expect(resolvePackageDir(join(root, 'app/package.json'), 'dep')).toBe(
			join(root, 'app/node_modules/dep'),
		);
	});

	test('walks up from the main entry when ./package.json is not exported', () => {
		const root = createFixture({
			'app/node_modules/dep/dist/nested/package.json': '{"type":"module"}',
			'app/node_modules/dep/dist/nested/index.js': '',
			'app/node_modules/dep/package.json': JSON.stringify({
				exports: { '.': './dist/nested/index.js' },
				name: 'dep',
			}),
			'app/package.json': '{"name":"app"}',
		});

		expect(resolvePackageDir(join(root, 'app/package.json'), 'dep')).toBe(
			join(root, 'app/node_modules/dep'),
		);
	});
});

// Prettier's TypeScript parser returns null for source that does not parse.
async function expectValidModule(source: string): Promise<void> {
	expect(await formatPlaygroundSource(source, {})).not.toBeNull();
}
