import type { SprinklesFn } from '@luke-ui/rainbow-sprinkles';
import { defineProperties, defineSprinkles } from '@luke-ui/rainbow-sprinkles';
import { vars } from '../theme/contract.css.js';
import { layers } from './layers.css.js';

const responsiveConditions = {
	xsmall: {},
	small: { '@media': 'screen and (width >= 640px)' },
	medium: { '@media': 'screen and (width >= 768px)' },
	large: { '@media': 'screen and (width >= 1024px)' },
	xlarge: { '@media': 'screen and (width >= 1280px)' },
	xxlarge: { '@media': 'screen and (width >= 1536px)' },
} as const;

const spaceScale = {
	'0': '0',
	'100': vars.space[100],
	'200': vars.space[200],
	'300': vars.space[300],
	'400': vars.space[400],
	'600': vars.space[600],
	'800': vars.space[800],
	'1000': vars.space[1000],
	'1200': vars.space[1200],
	'1600': vars.space[1600],
} as const;

const marginScale = { ...spaceScale, auto: 'auto' } as const;

const responsiveProperties = defineProperties({
	'@layer': layers.utilities,
	conditions: responsiveConditions,
	defaultCondition: 'xsmall',
	dynamicProperties: {
		alignContent: {
			center: 'center',
			'flex-end': 'flex-end',
			'flex-start': 'flex-start',
			normal: 'normal',
			'space-around': 'space-around',
			'space-between': 'space-between',
			stretch: 'stretch',
		},
		alignItems: {
			baseline: 'baseline',
			center: 'center',
			'flex-end': 'flex-end',
			'flex-start': 'flex-start',
			normal: 'normal',
			stretch: 'stretch',
		},
		alignSelf: {
			auto: 'auto',
			baseline: 'baseline',
			center: 'center',
			'flex-end': 'flex-end',
			'flex-start': 'flex-start',
			normal: 'normal',
			stretch: 'stretch',
		},
		blockSize: true,
		columnGap: spaceScale,
		display: {
			block: 'block',
			contents: 'contents',
			flex: 'flex',
			grid: 'grid',
			inline: 'inline',
			'inline-block': 'inline-block',
			'inline-flex': 'inline-flex',
			'inline-grid': 'inline-grid',
			none: 'none',
		},
		flex: true,
		flexBasis: true,
		flexDirection: {
			column: 'column',
			'column-reverse': 'column-reverse',
			row: 'row',
			'row-reverse': 'row-reverse',
		},
		flexGrow: { '0': '0', '1': '1' },
		flexShrink: { '0': '0', '1': '1' },
		flexWrap: { nowrap: 'nowrap', wrap: 'wrap', 'wrap-reverse': 'wrap-reverse' },
		gap: spaceScale,
		gridArea: true,
		gridColumn: true,
		gridColumnEnd: true,
		gridColumnStart: true,
		gridRow: true,
		gridRowEnd: true,
		gridRowStart: true,
		inlineSize: true,
		inset: true,
		insetBlock: true,
		insetBlockEnd: true,
		insetBlockStart: true,
		insetInline: true,
		insetInlineEnd: true,
		insetInlineStart: true,
		justifyContent: {
			center: 'center',
			'flex-end': 'flex-end',
			'flex-start': 'flex-start',
			normal: 'normal',
			'space-around': 'space-around',
			'space-between': 'space-between',
			'space-evenly': 'space-evenly',
			stretch: 'stretch',
		},
		justifySelf: {
			auto: 'auto',
			center: 'center',
			end: 'end',
			normal: 'normal',
			start: 'start',
			stretch: 'stretch',
		},
		margin: marginScale,
		marginBlock: marginScale,
		marginBlockEnd: marginScale,
		marginBlockStart: marginScale,
		marginInline: marginScale,
		marginInlineEnd: marginScale,
		marginInlineStart: marginScale,
		maxBlockSize: true,
		maxInlineSize: true,
		minBlockSize: true,
		minInlineSize: true,
		order: true,
		overflow: {
			auto: 'auto',
			clip: 'clip',
			hidden: 'hidden',
			scroll: 'scroll',
			visible: 'visible',
		},
		overflowX: {
			auto: 'auto',
			clip: 'clip',
			hidden: 'hidden',
			scroll: 'scroll',
			visible: 'visible',
		},
		overflowY: {
			auto: 'auto',
			clip: 'clip',
			hidden: 'hidden',
			scroll: 'scroll',
			visible: 'visible',
		},
		padding: spaceScale,
		paddingBlock: spaceScale,
		paddingBlockEnd: spaceScale,
		paddingBlockStart: spaceScale,
		paddingInline: spaceScale,
		paddingInlineEnd: spaceScale,
		paddingInlineStart: spaceScale,
		placeSelf: {
			auto: 'auto',
			center: 'center',
			end: 'end',
			normal: 'normal',
			start: 'start',
			stretch: 'stretch',
		},
		position: {
			absolute: 'absolute',
			fixed: 'fixed',
			relative: 'relative',
			static: 'static',
			sticky: 'sticky',
		},
		rowGap: spaceScale,
	},
});

export const createSprinkles: SprinklesFn<[typeof responsiveProperties]> =
	defineSprinkles(responsiveProperties);

export type SprinklesProps = Parameters<typeof createSprinkles>[0];
