import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const componentsDir = resolve(scriptDir, '../content/docs/components');

const META_JSON = `{
\t"pages": ["!props"],
\t"collapsible": false
}
`;

export interface PropsEntry {
	heading?: string;
	name: string;
	path: string;
}

export interface ComponentFrontmatter {
	/** Raw frontmatter lines for `description`, `reactAria`, `source`, and `title`, in file order. */
	copiedLines: ReadonlyArray<string>;
	props: ReadonlyArray<PropsEntry>;
}

/**
 * Emits each component's generated Props page and `meta.json` from the `props` frontmatter
 * declared on its `index.mdx`. `remarkAutoTypeTable` resolves types during MDX compilation and
 * `TypeTable` carries shiki-highlighted `ReactNode` fields, neither of which survives a loader
 * boundary, so the Props page is generated MDX rather than rendered from frontmatter at runtime.
 *
 * Only writes files whose content changed, and removes generated output for components that no
 * longer declare `props`.
 */
export function generatePropsPages(): { componentCount: number; removedCount: number } {
	let componentCount = 0;
	let removedCount = 0;

	for (const componentDir of findComponentDirs(componentsDir)) {
		const indexPath = resolve(componentDir, 'index.mdx');
		const propsPath = resolve(componentDir, 'props.mdx');
		const metaPath = resolve(componentDir, 'meta.json');

		const frontmatter = parseComponentFrontmatter(readFileSync(indexPath, 'utf8'));

		if (frontmatter.props.length === 0) {
			if (removeIfExists(propsPath)) removedCount++;
			if (removeIfExists(metaPath)) removedCount++;
			continue;
		}

		componentCount++;
		writeIfChanged(propsPath, renderPropsPage(frontmatter));
		writeIfChanged(metaPath, META_JSON);
	}

	return { componentCount, removedCount };
}

export function renderPropsPage(frontmatter: ComponentFrontmatter): string {
	const frontmatterBlock = frontmatter.copiedLines.join('\n');
	const entries = frontmatter.props
		.map((entry) => {
			const heading = entry.heading === undefined ? '' : `### ${entry.heading}\n\n`;
			return `${heading}${renderAutoTypeTable(entry)}`;
		})
		.join('\n\n');

	return `---
${frontmatterBlock}
---

{/* Generated by scripts/generate-props-pages.ts. Do not edit. */}

## Props

${entries}
`;
}

function renderAutoTypeTable(entry: PropsEntry): string {
	const inline = `<auto-type-table path="${entry.path}" name="${entry.name}" />`;
	if (inline.length <= 100) return inline;

	return `<auto-type-table\n\tpath="${entry.path}"\n\tname="${entry.name}"\n/>`;
}

export function parseComponentFrontmatter(contents: string): ComponentFrontmatter {
	const match = contents.match(/^---\n([\s\S]*?)\n---\n/);
	if (!match?.[1]) throw new Error('index.mdx is missing frontmatter');

	const lines = match[1].split('\n');
	const blocks = groupFrontmatterBlocks(lines);

	const copiedLines: Array<string> = [];
	let props: ReadonlyArray<PropsEntry> = [];

	for (const block of blocks) {
		if (block.key === 'props') {
			props = parsePropsEntries(block.lines);
			continue;
		}
		if (
			block.key === 'description' ||
			block.key === 'reactAria' ||
			block.key === 'source' ||
			block.key === 'title'
		) {
			copiedLines.push(...block.lines);
		}
	}

	return { copiedLines, props };
}

interface FrontmatterBlock {
	key: string;
	lines: ReadonlyArray<string>;
}

/** Splits frontmatter lines into top-level `key:` blocks, each carrying its indented continuation lines. */
function groupFrontmatterBlocks(lines: ReadonlyArray<string>): ReadonlyArray<FrontmatterBlock> {
	const blocks: Array<FrontmatterBlock> = [];

	for (const line of lines) {
		const topLevelKey = line.match(/^([A-Za-z]+):/)?.[1];
		if (topLevelKey !== undefined) {
			blocks.push({ key: topLevelKey, lines: [line] });
			continue;
		}

		const lastBlock = blocks[blocks.length - 1];
		if (lastBlock === undefined) throw new Error(`Frontmatter continuation with no key: ${line}`);
		(lastBlock.lines as Array<string>).push(line);
	}

	return blocks;
}

/** Parses a `props:` block's `- name: … / path: … / heading: …` list items, in file order. */
function parsePropsEntries(lines: ReadonlyArray<string>): ReadonlyArray<PropsEntry> {
	const entries: Array<Partial<PropsEntry>> = [];

	for (const line of lines) {
		const itemMatch = line.match(/^\s*-\s*(\w+):\s*(.+)$/);
		const fieldMatch = line.match(/^\s+(\w+):\s*(.+)$/);

		if (itemMatch?.[1] !== undefined && itemMatch[2] !== undefined) {
			entries.push({ [itemMatch[1]]: itemMatch[2] });
			continue;
		}

		if (fieldMatch?.[1] !== undefined && fieldMatch[2] !== undefined) {
			const lastEntry = entries[entries.length - 1];
			if (lastEntry === undefined) throw new Error(`props field with no entry: ${line}`);
			Object.assign(lastEntry, { [fieldMatch[1]]: fieldMatch[2] });
		}
	}

	return entries.map((entry) => {
		if (entry.name === undefined) throw new Error('props entry is missing name');
		if (entry.path === undefined) throw new Error('props entry is missing path');
		return { heading: entry.heading, name: entry.name, path: entry.path };
	});
}

function findComponentDirs(directory: string): ReadonlyArray<string> {
	const dirs: Array<string> = [];

	for (const group of readdirSync(directory, { withFileTypes: true })) {
		if (!group.isDirectory()) continue;
		const groupDir = resolve(directory, group.name);

		for (const component of readdirSync(groupDir, { withFileTypes: true })) {
			if (!component.isDirectory()) continue;
			const componentDir = resolve(groupDir, component.name);
			if (existsSync(resolve(componentDir, 'index.mdx'))) dirs.push(componentDir);
		}
	}

	return dirs.sort();
}

function writeIfChanged(filepath: string, content: string): boolean {
	try {
		const current = readFileSync(filepath, 'utf8');
		if (current === content) return false;
	} catch {
		// File doesn't exist yet.
	}
	writeFileSync(filepath, content, 'utf8');
	return true;
}

function removeIfExists(filepath: string): boolean {
	if (!existsSync(filepath)) return false;
	rmSync(filepath);
	return true;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	mkdirSync(componentsDir, { recursive: true });
	const { componentCount, removedCount } = generatePropsPages();
	// oxlint-disable-next-line no-console
	console.log(
		`generate-props-pages: wrote props pages for ${componentCount} components${removedCount > 0 ? `, removed ${removedCount} stale files` : ''}`,
	);
}
