/**
 * Generates src/generated/playground-scope.generated.ts — the module map the
 * playground preview uses to resolve imports in user code at runtime.
 *
 * Reads the `exports` map of @luke-ui/react so new component subpaths are
 * picked up automatically. Runs via the `generate:playground` script (wired
 * into `docs#generate` in turbo.json), so dev and build always regenerate it.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const reactPackageJsonPath = resolve(scriptDir, '../../../packages/@luke-ui/react/package.json');
const outputPath = resolve(scriptDir, '../src/generated/playground-scope.generated.ts');

const packageJsonSchema = z.object({
	exports: z.record(z.string(), z.string()),
});

const reactPackageJson = packageJsonSchema.parse(
	JSON.parse(readFileSync(reactPackageJsonPath, 'utf8')),
);

const lukeUiSpecifiers = Object.keys(reactPackageJson.exports)
	.flatMap((key) => {
		const target = reactPackageJson.exports[key];
		if (key === './package.json' || target === undefined || !target.endsWith('.js')) return [];
		return [`@luke-ui/react/${key.slice(2)}`];
	})
	.sort();

const baseSpecifiers = ['react', 'react-dom', 'react-dom/client', 'react/jsx-runtime'];
const specifiers = [...lukeUiSpecifiers, ...baseSpecifiers];

const SPECIFIER_TO_IDENTIFIER_RE = /^@|[^a-zA-Z0-9]+/g;

function toIdentifier(specifier: string): string {
	return specifier.replace(SPECIFIER_TO_IDENTIFIER_RE, (match) => (match === '@' ? '' : '_'));
}

const importLines = specifiers.map(
	(specifier) => `import * as ${toIdentifier(specifier)} from '${specifier}';`,
);
const entryLines = specifiers.map((specifier) => `\t'${specifier}': ${toIdentifier(specifier)},`);

const output = `// Generated by scripts/generate-playground-scope.ts — do not edit.
${importLines.join('\n')}

export const playgroundScope: Record<string, unknown> = {
${entryLines.join('\n')}
};
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output);
// oxlint-disable-next-line no-console
console.log(
	`generate-playground-scope: wrote ${specifiers.length} modules to src/generated/playground-scope.generated.ts`,
);
