/**
 * Generates src/generated/playground-scope.generated.ts — the module map the
 * playground preview uses to resolve imports in user code at runtime.
 *
 * Reads the specifier list from `playground-runtime-specifiers.ts` so new
 * `@luke-ui/react` subpaths and the shared third-party allowlist stay in one
 * place. Runs via the `generate:playground` script (wired into `docs#generate`
 * in turbo.json), so dev and build always regenerate it.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { playgroundRuntimeSpecifierList } from '../src/lib/playground-runtime-specifiers.js';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(scriptDir, '../src/generated/playground-scope.generated.ts');

const specifiers = playgroundRuntimeSpecifierList();

const SPECIFIER_TO_IDENTIFIER_RE = /^@|[^a-zA-Z0-9]+/g;

function toIdentifier(specifier: string): string {
	return specifier.replace(SPECIFIER_TO_IDENTIFIER_RE, (match) => (match === '@' ? '' : '_'));
}

const importLines = specifiers.map(
	(specifier) => `import * as ${toIdentifier(specifier)} from '${specifier}';`,
);
const entryLines = specifiers.map((specifier) => `\t'${specifier}': ${toIdentifier(specifier)},`);

const output = `// Generated by scripts/generate-playground-scope.ts — do not edit.
${importLines.join('\n')}

export const playgroundScope: Record<string, unknown> = {
${entryLines.join('\n')}
};
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output);
// oxlint-disable-next-line no-console
console.log(
	`generate-playground-scope: wrote ${specifiers.length} modules to src/generated/playground-scope.generated.ts`,
);
