import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const contractPath = resolve(scriptDir, '../../../packages/@luke-ui/react/src/theme/contract.ts');
const outputPath = resolve(scriptDir, '../src/generated/token-reference.generated.ts');
const { flattenThemeContract } = (await import(contractPath)) as {
	flattenThemeContract: () => Array<[path: string, variable: string]>;
};

interface GeneratedToken {
	family: string;
	path: string;
	variable: string;
}

/**
 * Emits the docs app's single runtime source of truth for the public token contract: one entry per
 * contract leaf, plus the family union those entries are keyed by. The token explorer renders from
 * this array, so the documented set can never drift from the set `flattenThemeContract()` produces.
 */
export function generateTokenReference(): string {
	const descriptions = readFamilyDescriptions(readFileSync(contractPath, 'utf8'));
	const tokens = flattenThemeContract().map(([path, variable]): GeneratedToken => {
		const family = path.split('.')[0];
		if (family === undefined) throw new Error(`Theme contract path "${path}" has no family`);
		if (!descriptions.has(family)) throw new Error(`Missing JSDoc for theme family "${family}"`);
		return { family, path, variable };
	});
	const families = [...new Set(tokens.map((token) => token.family))];

	const familyUnion = families.map((family) => `\n\t| ${quote(family)}`).join('');
	const tokenEntries = tokens
		.map(
			({ family, path, variable }) =>
				`\t{ family: ${quote(family)}, path: ${quote(path)}, variable: ${quote(variable)} },`,
		)
		.join('\n');
	const familyEntries = families
		.map((family) => `\t${quote(family)}: ${quote(collapseWhitespace(descriptions.get(family)))},`)
		.join('\n');

	return `// Generated by scripts/generate-token-reference.ts — do not edit.

/** A top-level branch of the public theme contract, for example \`color\` or \`motion\`. */
export type ThemeTokenFamily =${familyUnion};

/** One public token: the \`vars\` path and the \`--luke-*\` custom property it resolves to. */
export interface ThemeToken {
	family: ThemeTokenFamily;
	path: string;
	variable: string;
}

/** Every leaf of the public theme contract, in contract order. */
export const themeTokens: ReadonlyArray<ThemeToken> = [
${tokenEntries}
];

/** The theme contract's own summary of each family, keyed by family name. */
export const themeTokenFamilyDescriptions: Record<ThemeTokenFamily, string> = {
${familyEntries}
};
`;
}

function collapseWhitespace(text: string | undefined): string {
	return (text ?? '').replace(/\s+/g, ' ').trim();
}

function quote(text: string): string {
	return `'${text.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

function readFamilyDescriptions(source: string): Map<string, string> {
	const sourceFile = ts.createSourceFile(contractPath, source, ts.ScriptTarget.Latest, true);
	const declaration = sourceFile.statements.find(
		(statement): statement is ts.VariableStatement =>
			ts.isVariableStatement(statement) &&
			statement.declarationList.declarations.some(
				(item) => ts.isIdentifier(item.name) && item.name.text === 'themeContractTree',
			),
	);
	const initializer = declaration?.declarationList.declarations.find(
		(item) => ts.isIdentifier(item.name) && item.name.text === 'themeContractTree',
	)?.initializer;
	if (!initializer || !ts.isObjectLiteralExpression(initializer)) {
		throw new Error('Could not find the themeContractTree object literal');
	}

	const descriptions = new Map<string, string>();
	for (const property of initializer.properties) {
		if (!ts.isPropertyAssignment(property)) continue;
		const name = property.name.getText(sourceFile).replaceAll("'", '');
		const jsDoc = ts.getJSDocCommentsAndTags(property).find(ts.isJSDoc);
		if (typeof jsDoc?.comment === 'string') descriptions.set(name, jsDoc.comment);
	}
	return descriptions;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const output = generateTokenReference();
	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, output);
	// oxlint-disable-next-line no-console
	console.log(`generate-token-reference: wrote ${flattenThemeContract().length} token entries`);
}
