import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const componentsDir = resolve(scriptDir, '../content/docs/components');
const outputPath = resolve(scriptDir, '../src/generated/components-index.generated.ts');

interface ComponentIndexEntry {
	description: string;
	name: string;
	url: string;
}

interface ComponentIndexGroup {
	entries: Array<ComponentIndexEntry>;
	title: string;
}

/**
 * Emits the docs app's single runtime source of truth for the component catalogue: one entry per
 * component guide, grouped by category in sidebar order. The components landing page renders from
 * this array, so the documented set can never drift from the guides that live on disk.
 */
export function generateComponentsIndex(): string {
	const groups = readGroups();

	const groupEntries = groups
		.map(
			(group) => `\t{
\t\ttitle: ${quote(group.title)},
\t\tentries: [
${group.entries
	.map(
		(entry) =>
			`\t\t\t{ description: ${quote(entry.description)}, name: ${quote(entry.name)}, url: ${quote(entry.url)} },`,
	)
	.join('\n')}
\t\t],
\t},`,
		)
		.join('\n');

	return `// Generated by scripts/generate-components-index.ts — do not edit.

/** One component guide: its title, one-line description, and URL. */
export interface ComponentIndexEntry {
	description: string;
	name: string;
	url: string;
}

/** A component category with its guides, in sidebar order. */
export interface ComponentIndexGroup {
	entries: ReadonlyArray<ComponentIndexEntry>;
	title: string;
}

/** Every component guide, grouped by category, in sidebar order. */
export const componentIndexGroups: ReadonlyArray<ComponentIndexGroup> = [
${groupEntries}
];
`;
}

function readGroups(): ReadonlyArray<ComponentIndexGroup> {
	const rootMeta = readJson(resolve(componentsDir, 'meta.json')) as { pages?: Array<string> };
	const entries = rootMeta.pages ?? [];
	const groups: Array<ComponentIndexGroup> = [];
	let currentTitle = 'Components';

	for (const entry of entries) {
		if (isSeparator(entry)) {
			currentTitle = entry.slice(3, -3);
			groups.push({ entries: [], title: currentTitle });
			continue;
		}

		const guidePath = resolve(componentsDir, `${entry}/index.mdx`);
		if (!existsSync(guidePath)) continue;

		const frontmatter = readFrontmatter(readFileSync(guidePath, 'utf8'));
		let lastGroup = groups[groups.length - 1];
		if (!lastGroup) {
			lastGroup = { entries: [], title: currentTitle };
			groups.push(lastGroup);
		}

		lastGroup.entries.push({
			description: frontmatter.description ?? '',
			name: frontmatter.title ?? entry,
			url: `/components/${entry}`,
		});
	}

	return groups;
}

function isSeparator(value: string): boolean {
	return /^---.+---$/.test(value);
}

function readJson(path: string): unknown {
	return JSON.parse(readFileSync(path, 'utf8'));
}

function readFrontmatter(contents: string): { description?: string; title?: string } {
	const frontmatter = contents.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? '';

	return {
		description: readFrontmatterValue(frontmatter, 'description'),
		title: readFrontmatterValue(frontmatter, 'title'),
	};
}

function readFrontmatterValue(
	frontmatter: string,
	key: 'description' | 'title',
): string | undefined {
	const lines = frontmatter.split('\n');
	const keyPrefix = `${key}:`;

	for (const [index, line] of lines.entries()) {
		if (!line.startsWith(keyPrefix)) continue;

		const inlineValue = line.slice(keyPrefix.length).trim();
		if (inlineValue) return inlineValue;

		const continuation: Array<string> = [];
		for (const nextLine of lines.slice(index + 1)) {
			if (!nextLine.startsWith(' ')) break;
			continuation.push(nextLine.trim());
		}

		return continuation.join(' ');
	}

	return undefined;
}

function quote(text: string): string {
	return `'${text.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const output = generateComponentsIndex();
	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, output);
	const entryCount = readGroups().flatMap((group) => group.entries).length;
	// oxlint-disable-next-line no-console
	console.log(`generate-components-index: wrote ${entryCount} entries`);
}
