import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const contractPath = resolve(scriptDir, '../../../packages/@luke-ui/react/src/theme/contract.ts');
const outputPath = resolve(scriptDir, '../src/generated/token-reference.generated.ts');
const { flattenThemeContract } = (await import(contractPath)) as {
	flattenThemeContract: () => Array<[path: string, variable: string]>;
};

export function generateTokenReference(): string {
	const descriptions = readFamilyDescriptions(readFileSync(contractPath, 'utf8'));
	const entries = flattenThemeContract().map(([path, variable]) => {
		const family = path.split('.')[0];
		const description = family === undefined ? undefined : descriptions.get(family);
		if (description === undefined) throw new Error(`Missing JSDoc for theme family "${family}"`);
		return `\t/**\n\t * ${description}\n\t * CSS variable: \`${variable}\`.\n\t */\n\t'${path}': 'var(${variable})';`;
	});

	return `// Generated by scripts/generate-token-reference.ts — do not edit.\n\nexport interface ThemeTokenReference {\n${entries.join('\n')}\n}\n`;
}

function readFamilyDescriptions(source: string): Map<string, string> {
	const sourceFile = ts.createSourceFile(contractPath, source, ts.ScriptTarget.Latest, true);
	const declaration = sourceFile.statements.find(
		(statement): statement is ts.VariableStatement =>
			ts.isVariableStatement(statement) &&
			statement.declarationList.declarations.some(
				(item) => ts.isIdentifier(item.name) && item.name.text === 'themeContractTree',
			),
	);
	const initializer = declaration?.declarationList.declarations.find(
		(item) => ts.isIdentifier(item.name) && item.name.text === 'themeContractTree',
	)?.initializer;
	if (!initializer || !ts.isObjectLiteralExpression(initializer)) {
		throw new Error('Could not find the themeContractTree object literal');
	}

	const descriptions = new Map<string, string>();
	for (const property of initializer.properties) {
		if (!ts.isPropertyAssignment(property)) continue;
		const name = property.name.getText(sourceFile).replaceAll("'", '');
		const jsDoc = ts.getJSDocCommentsAndTags(property).find(ts.isJSDoc);
		if (typeof jsDoc?.comment === 'string') descriptions.set(name, jsDoc.comment);
	}
	return descriptions;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const output = generateTokenReference();
	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, output);
	// oxlint-disable-next-line no-console
	console.log(`generate-token-reference: wrote ${flattenThemeContract().length} token entries`);
}
