import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmdirSync,
	rmSync,
	writeFileSync,
} from 'node:fs';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ComponentFrontmatter, PropsEntry } from '../src/lib/docs-frontmatter.ts';
import { parseComponentFrontmatter } from '../src/lib/docs-frontmatter.ts';
import { findMdxFiles } from '../src/lib/docs-mdx-files.ts';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const componentsDir = resolve(scriptDir, '../content/docs/components');

/**
 * Fumadocs joins `pagesIndex` to this folder. `../<name>` is the sibling authored guide, which
 * becomes the folder's clickable index.
 */
function renderMetaJson(componentName: string): string {
	return `{
\t"pages": ["!props"],
\t"collapsible": false,
\t"pagesIndex": "../${componentName}"
}
`;
}

/**
 * Emits each component's generated Props page and `meta.json` from the `props` frontmatter
 * declared on its `<group>/<name>.mdx` guide. `remarkAutoTypeTable` resolves types during MDX
 * compilation and `TypeTable` carries shiki-highlighted `ReactNode` fields, neither of which
 * survives a loader boundary, so the Props page is generated MDX rather than rendered from
 * frontmatter at runtime.
 *
 * Only writes files whose content changed, and removes generator-owned output for components that
 * do not declare `props` or whose guide is missing.
 */
export function generatePropsPages(rootDir: string = componentsDir): {
	componentCount: number;
	removedCount: number;
} {
	let componentCount = 0;
	let removedCount = 0;

	for (const group of readdirSync(rootDir, { withFileTypes: true })) {
		if (!group.isDirectory()) continue;
		const groupDir = resolve(rootDir, group.name);

		for (const componentName of discoverComponentNames(groupDir)) {
			const guidePath = resolve(groupDir, `${componentName}.mdx`);
			const outputDir = resolve(groupDir, componentName);
			const propsPath = resolve(outputDir, 'props.mdx');
			const metaPath = resolve(outputDir, 'meta.json');

			if (!existsSync(guidePath)) {
				if (removeIfExists(propsPath)) removedCount++;
				if (removeIfExists(metaPath)) removedCount++;
				removeDirIfEmpty(outputDir);
				continue;
			}

			const frontmatter = parseComponentFrontmatter(readFileSync(guidePath, 'utf8'));

			if (frontmatter.props.length === 0) {
				if (removeIfExists(propsPath)) removedCount++;
				if (removeIfExists(metaPath)) removedCount++;
				removeDirIfEmpty(outputDir);
				continue;
			}

			componentCount++;
			mkdirSync(outputDir, { recursive: true });
			writeIfChanged(propsPath, renderPropsPage(frontmatter));
			writeIfChanged(metaPath, renderMetaJson(componentName));
		}
	}

	return { componentCount, removedCount };
}

export function renderPropsPage(frontmatter: ComponentFrontmatter): string {
	const frontmatterBlock = frontmatter.copiedLines.join('\n');
	const withTypeHeadings = frontmatter.props.length > 1;
	const entries = frontmatter.props
		.map((entry) => {
			const table = renderAutoTypeTable(entry);
			return withTypeHeadings ? `### ${entry.name}\n\n${table}` : table;
		})
		.join('\n\n');

	return `---
${frontmatterBlock}
---

{/* Generated by scripts/generate-props-pages.ts. Do not edit. */}

## Props

${entries}
`;
}

function renderAutoTypeTable(entry: PropsEntry): string {
	const inline = `<auto-type-table path="${entry.path}" name="${entry.name}" />`;
	if (inline.length <= 100) return inline;

	return `<auto-type-table\n\tpath="${entry.path}"\n\tname="${entry.name}"\n/>`;
}

/**
 * Every component name in a group: the union of authored `*.mdx` guides and existing directories,
 * so stale generated output is still discovered after a guide is deleted or renamed.
 */
function discoverComponentNames(groupDir: string): ReadonlyArray<string> {
	const names = new Set<string>();

	for (const entry of readdirSync(groupDir, { withFileTypes: true })) {
		if (entry.isDirectory()) names.add(entry.name);
	}

	for (const file of findMdxFiles(groupDir)) {
		if (dirname(file) !== groupDir) continue;
		names.add(basename(file, '.mdx'));
	}

	return [...names].sort();
}

function writeIfChanged(filepath: string, content: string): boolean {
	try {
		const current = readFileSync(filepath, 'utf8');
		if (current === content) return false;
	} catch {
		// File doesn't exist yet.
	}
	writeFileSync(filepath, content, 'utf8');
	return true;
}

function removeIfExists(filepath: string): boolean {
	if (!existsSync(filepath)) return false;
	rmSync(filepath);
	return true;
}

/** Removes the component output directory when it is empty. */
function removeDirIfEmpty(dirPath: string): void {
	if (!existsSync(dirPath)) return;
	if (readdirSync(dirPath).length > 0) return;
	rmdirSync(dirPath);
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	mkdirSync(componentsDir, { recursive: true });
	const { componentCount, removedCount } = generatePropsPages();
	// oxlint-disable-next-line no-console
	console.log(
		`generate-props-pages: wrote props pages for ${componentCount} components${removedCount > 0 ? `, removed ${removedCount} stale files` : ''}`,
	);
}
