#!/usr/bin/env tsx

import fs from 'node:fs';
import path from 'node:path';
import { parse } from 'node-html-parser';

const DEFAULT_VIEWBOX = '0 0 24 24';
const SPRITE_NAME = 'spritesheet.svg';
const INPUT_DIR = path.resolve(process.cwd(), 'icons');
const OUTPUT_DIR = path.resolve(process.cwd(), 'dist');
const GENERATED_DIR = path.resolve(process.cwd(), '.generated');
const ICON_DATA_TS_PATH = path.resolve(GENERATED_DIR, 'icon-data.ts');
const ICON_MASK_DATA_TS_PATH = path.resolve(GENERATED_DIR, 'icon-mask-data.ts');

async function writeIfChanged(filepath: string, content: string): Promise<boolean> {
	try {
		const current = await fs.promises.readFile(filepath, 'utf8');
		if (current === content) return false;
	} catch {
		// File doesn't exist yet
	}
	await fs.promises.writeFile(filepath, content, 'utf8');
	return true;
}

async function main() {
	fs.mkdirSync(OUTPUT_DIR, { recursive: true });
	fs.mkdirSync(GENERATED_DIR, { recursive: true });

	if (!fs.existsSync(INPUT_DIR)) {
		process.stdout.write(`No input directory found: ${INPUT_DIR}\n`);
		return;
	}

	const svgFiles = fs
		.readdirSync(INPUT_DIR)
		.filter((f) => f.endsWith('.svg'))
		.sort();

	if (svgFiles.length === 0) {
		process.stdout.write(`No SVG files found in: ${INPUT_DIR}\n`);
		return;
	}

	const symbols: Array<string> = [];
	const viewBoxes: Record<string, string> = {};
	const iconNames: Array<string> = [];
	const seenIconNames = new Set<string>();
	// Standalone SVG source per icon, `currentColor` forced to an opaque colour so
	// it survives as a CSS mask image: `mask-image` masks by alpha channel, not by
	// the resolved colour, but `currentColor` in a detached data-URI document has
	// no ancestor to inherit from, so it must be replaced with a literal colour to
	// render as opaque at all.
	const maskSources: Record<string, string> = {};

	for (const file of svgFiles) {
		const iconName = path.basename(file, '.svg');
		const filePath = path.join(INPUT_DIR, file);

		try {
			const svgContent = fs.readFileSync(filePath, 'utf8');
			const root = parse(svgContent);
			const svg = root.querySelector('svg');

			if (!svg) {
				process.stdout.write(`Skipping "${file}": no <svg> element found\n`);
				continue;
			}

			if (seenIconNames.has(iconName)) {
				process.stdout.write(`Skipping "${file}": duplicate icon id "${iconName}"\n`);
				continue;
			}

			const viewBox = svg.getAttribute('viewBox') ?? DEFAULT_VIEWBOX;

			svg.tagName = 'symbol';
			svg.setAttribute('id', iconName);
			svg.removeAttribute('xmlns');
			svg.removeAttribute('xmlns:xlink');
			svg.removeAttribute('version');
			svg.removeAttribute('width');
			svg.removeAttribute('height');

			seenIconNames.add(iconName);
			iconNames.push(iconName);
			viewBoxes[iconName] = viewBox;
			symbols.push(svg.toString());
			maskSources[iconName] = svgContent.replaceAll('currentColor', 'black');
		} catch (err) {
			const message = err instanceof Error ? err.message : String(err);
			process.stdout.write(`Failed to read "${file}": ${message}\n`);
		}
	}

	if (iconNames.length === 0) {
		process.stdout.write('No valid SVGs found after parsing\n');
		return;
	}

	const sprite = [
		'<?xml version="1.0" encoding="UTF-8"?>',
		'<svg xmlns="http://www.w3.org/2000/svg" height="0" width="0">',
		'<defs>',
		...symbols,
		'</defs>',
		'</svg>',
		'',
	].join('\n');

	const iconDataTs = `/* This file is generated by scripts/build-icons.ts */

export const iconNames = [${iconNames.map((n) => `'${n}'`).join(', ')}] as const;

export type IconName = (typeof iconNames)[number];

export const iconViewBoxes: Record<IconName, string> = {
${iconNames.map((n) => `\t'${n}': '${viewBoxes[n]}'`).join(',\n')}
} as const;
`;

	// Kept separate from `icon-data.ts`: that module is imported at runtime by the
	// `Icon` component, so inlining every icon's SVG source into it would drag all
	// of them into the client bundle. This module is only imported by build-time
	// `.css.ts` files, and only the icons a recipe actually references reach the
	// shipped CSS.
	const iconMaskDataTs = `/* This file is generated by scripts/build-icons.ts */

import type { IconName } from './icon-data.js';

export const iconMaskUrls: Record<IconName, string> = {
${iconNames.map((n) => `\t'${n}': 'url("data:image/svg+xml,${encodeURIComponent(maskSources[n] ?? '')}")'`).join(',\n')}
} as const;
`;

	const spritePath = path.join(OUTPUT_DIR, SPRITE_NAME);
	const [spriteChanged, iconDataChanged, iconMaskDataChanged] = await Promise.all([
		writeIfChanged(spritePath, sprite),
		writeIfChanged(ICON_DATA_TS_PATH, iconDataTs),
		writeIfChanged(ICON_MASK_DATA_TS_PATH, iconMaskDataTs),
	]);

	const changed = spriteChanged || iconDataChanged || iconMaskDataChanged;
	if (changed) {
		process.stdout.write(`Generated spritesheet with ${iconNames.length} icons\n`);
	} else {
		process.stdout.write(`Spritesheet up to date (${iconNames.length} icons)\n`);
	}
}

main().catch((err) => {
	const message = err instanceof Error ? (err.stack ?? err.message) : String(err);
	process.stderr.write(`Failed to build icons: ${message}\n`);
	process.exit(1);
});
