import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FONT_METRIC_SCALE } from '../src/theme/font-metric-scale.js';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(scriptDir, '../src/theme/font-metric-scale.stylex.ts');

export function generateFontMetricConsts(): string {
	const steps = Object.keys(FONT_METRIC_SCALE)
		.map(Number)
		.sort((a, b) => a - b);

	const lines = steps.flatMap((step) => {
		const metric = FONT_METRIC_SCALE[step as keyof typeof FONT_METRIC_SCALE];
		return [
			`\tstep${step}: {`,
			`\t\tfontSize: '${metric.fontSize}',`,
			`\t\tletterSpacing: '${metric.letterSpacing}',`,
			`\t\tlineHeight: '${metric.lineHeight}',`,
			`\t},`,
		];
	});

	return `// Generated by scripts/generate-font-metric-consts.ts — do not edit.

import * as stylex from '@stylexjs/stylex';

/**
 * StyleX-importable mirror of \`FONT_METRIC_SCALE\` (\`font-metric-scale.ts\`), which stays the only
 * authored source — this file is NOT the source of truth. StyleX can only import values from a
 * \`.stylex.ts\` module, and \`font-metric-scale.ts\` must stay plain TypeScript so \`build-themes.ts\`
 * and \`token-values.ts\` can import it under \`tsx\` without a Babel step, so the scale is
 * flattened and mirrored here at generation time instead of imported directly.
 *
 * Keys are prefixed with \`step\` (e.g. \`step12\`, \`step14\`) rather than left as bare numbers,
 * because a numeric key would force bracket access (\`fontMetrics[12].fontSize\`) — the prefix
 * keeps every read plain dot notation, matching the authored scale's own metric-step vocabulary.
 */
export const fontMetrics = stylex.unstable_defineConstsNested({
${lines.join('\n')}
});
`;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const output = generateFontMetricConsts();
	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, output);
	// oxlint-disable-next-line no-console
	console.log(`generate-font-metric-consts: wrote ${Object.keys(FONT_METRIC_SCALE).length} steps`);
}
