import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const contractPath = resolve(scriptDir, '../src/theme/contract.ts');
const outputPath = resolve(scriptDir, '../src/theme/tokens.stylex.ts');
const { flattenThemeContract } = (await import(contractPath)) as {
	flattenThemeContract: () => Array<[path: string, variable: string]>;
};

function toCamelCaseKey(path: string): string {
	const [first, ...rest] = path.split('.');
	if (first === undefined) throw new Error(`Theme contract path "${path}" is empty`);
	return first + rest.map((segment) => segment[0]?.toUpperCase() + segment.slice(1)).join('');
}

export function generateStylexTokens(): string {
	const entries = flattenThemeContract().map(([path, variable]) => {
		const key = toCamelCaseKey(path);
		return `\t${key}: 'var(${variable})',`;
	});

	return `// Generated by scripts/generate-stylex-tokens.ts — do not edit.

import * as stylex from '@stylexjs/stylex';

/** Compiler-facing StyleX token surface. Each value is a live \`var(--luke-*)\` reference. */
export const tokens = stylex.defineConsts({
${entries.join('\n')}
});
`;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const output = generateStylexTokens();
	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, output);
	// oxlint-disable-next-line no-console
	console.log(`generate-stylex-tokens: wrote ${flattenThemeContract().length} token entries`);
}
