import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const contractPath = resolve(scriptDir, '../src/theme/contract.ts');
const outputPath = resolve(scriptDir, '../src/theme/tokens.stylex.ts');
const { themeContractTree, themeVarName, flattenThemeContract } = (await import(contractPath)) as {
	themeContractTree: Record<string, unknown>;
	themeVarName: (segments: Array<string>) => string;
	flattenThemeContract: () => Array<[path: string, variable: string]>;
};

/**
 * Renders one contract node as a statically-analyzable nested object literal, indenting each level
 * with tabs so StyleX's compiler can read the object shape directly from source.
 */
function renderNode(node: Record<string, unknown>, segments: Array<string>, depth: number): string {
	const indent = '\t'.repeat(depth);
	const childIndent = '\t'.repeat(depth + 1);
	const lines = Object.entries(node).map(([key, value]) => {
		const path = [...segments, key];
		if (value === null) return `${childIndent}${key}: 'var(${themeVarName(path)})',`;
		return `${childIndent}${key}: ${renderNode(value as Record<string, unknown>, path, depth + 1)},`;
	});
	return `{\n${lines.join('\n')}\n${indent}}`;
}

export function generateStylexTokens(): string {
	const body = renderNode(themeContractTree, [], 0);

	return `// Generated by scripts/generate-stylex-tokens.ts — do not edit.

import * as stylex from '@stylexjs/stylex';

/**
 * The one theme token interface: nested paths such as \`vars.color.background.danger.solid.hover\`
 * mirror the theme contract tree exactly. Each leaf is a live \`var(--luke-*)\` reference. Used by
 * StyleX recipes, remaining Vanilla Extract styles, and re-exported as the public
 * \`@luke-ui/react/theme\` \`vars\`.
 */
export const vars = stylex.unstable_defineConstsNested(${body});
`;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const output = generateStylexTokens();
	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, output);
	// oxlint-disable-next-line no-console
	console.log(`generate-stylex-tokens: wrote ${flattenThemeContract().length} token entries`);
}
