#!/usr/bin/env tsx

import path from 'node:path';
import fs from 'node:fs/promises';

const PACKAGE_ROOT = process.cwd();
const SRC_ROOT = path.resolve(PACKAGE_ROOT, 'src');
const OUTPUT_DIR = path.resolve(PACKAGE_ROOT, '.generated');
const OUTPUT_TS = path.join(OUTPUT_DIR, 'entries.ts');

const extraEntries: Record<string, string> = {
	recipes: 'src/recipes/primitives.ts',
	styles: 'src/styles/index.css.ts',
	theme: 'src/theme/theme.tsx',
	tokens: 'src/tokens.ts',
	utils: 'src/utils.ts',
};

async function writeIfChanged(
	filePath: string,
	content: string,
): Promise<boolean> {
	try {
		const current = await fs.readFile(filePath, 'utf8');
		if (current === content) return false;
	} catch {
		// File missing; write it.
	}
	await fs.writeFile(filePath, content, 'utf8');
	return true;
}

async function fileExists(filePath: string): Promise<boolean> {
	try {
		await fs.access(filePath);
		return true;
	} catch {
		return false;
	}
}

async function collectGroupEntries(): Promise<Record<string, string>> {
	const sourceDirs = await fs.readdir(SRC_ROOT, { withFileTypes: true });
	const groupNames = sourceDirs
		.filter((dirent) => dirent.isDirectory())
		.map((dirent) => dirent.name);

	const groupEntries = (
		await Promise.all(
			groupNames.map(async (groupName) => {
				const primitivesPath = path.join(SRC_ROOT, groupName, 'primitives.ts');
				const composedPath = path.join(SRC_ROOT, groupName, 'composed.ts');
				const [hasPrimitives, hasComposed] = await Promise.all([
					fileExists(primitivesPath),
					fileExists(composedPath),
				]);

				const entries: Array<[string, string]> = [];
				if (hasPrimitives) {
					entries.push([
						groupName,
						path
							.relative(PACKAGE_ROOT, primitivesPath)
							.replaceAll(path.sep, '/'),
					]);
				}
				if (hasComposed) {
					entries.push([
						`${groupName}/composed`,
						path.relative(PACKAGE_ROOT, composedPath).replaceAll(path.sep, '/'),
					]);
				}
				return entries;
			}),
		)
	).flat();

	return Object.fromEntries(groupEntries);
}

async function assertEntryFilesExist(
	entries: Record<string, string>,
): Promise<void> {
	await Promise.all(
		Object.entries(entries).map(async ([subpath, relativePath]) => {
			const absolutePath = path.resolve(PACKAGE_ROOT, relativePath);
			try {
				await fs.access(absolutePath);
			} catch {
				throw new Error(
					`Entry "${subpath}" points to missing file: ${relativePath}`,
				);
			}
		}),
	);
}

function createTsModule(entries: Record<string, string>): string {
	const body = Object.entries(entries)
		.map(([subpath, sourcePath]) => `\t'${subpath}': '${sourcePath}',`)
		.join('\n');
	const aliasBody = Object.entries({
		...entries,
		'spritesheet.svg': 'dist/spritesheet.svg',
		'stylesheet.css': 'src/styles/index.css.ts',
	})
		.map(([subpath, sourcePath]) => `\t'${subpath}': '${sourcePath}',`)
		.join('\n');

	return `/* This file is generated by scripts/generate-entries.ts */
export const entries = {
${body}
} as const satisfies Record<string, string>;

export const devEntries = {
${aliasBody}
} as const satisfies Record<string, string>;
`;
}

async function main() {
	const groupEntries = await collectGroupEntries();
	const entries = Object.fromEntries(
		Object.entries({
			...groupEntries,
			...extraEntries,
		}).sort(([a], [b]) => a.localeCompare(b)),
	);

	await assertEntryFilesExist(entries);
	await fs.mkdir(OUTPUT_DIR, { recursive: true });

	const tsChanged = await writeIfChanged(OUTPUT_TS, createTsModule(entries));

	if (tsChanged) {
		process.stdout.write(
			`Generated entries (${Object.keys(entries).length})\n`,
		);
	} else {
		process.stdout.write(
			`Entries up to date (${Object.keys(entries).length})\n`,
		);
	}
}

main().catch((err) => {
	const errorMessage =
		err instanceof Error ? (err.stack ?? err.message) : String(err);
	process.stderr.write(`Failed to generate entries: ${errorMessage}\n`);
	process.exit(1);
});
