// Generated by scripts/generate-font-metric-consts.ts — do not edit.

import * as stylex from '@stylexjs/stylex';

/**
 * StyleX-importable mirror of `FONT_METRIC_SCALE` (`font-metric-scale.ts`), which stays the only
 * authored source — this file is NOT the source of truth. StyleX can only import values from a
 * `.stylex.ts` module, and `font-metric-scale.ts` must stay plain TypeScript so `build-themes.ts`
 * and `token-values.ts` can import it under `tsx` without a Babel step, so the scale is
 * flattened and mirrored here at generation time instead of imported directly.
 *
 * Flat `<metric><step>` keys (e.g. `fontSize12`, `letterSpacing12`, `lineHeight12`) rather than
 * a nested `fontMetrics[12].fontSize` shape, because StyleX's compiler needs a statically
 * indexable member expression and cannot resolve a computed numeric key.
 */
export const fontMetrics = stylex.defineConsts({
	fontSize12: '12px',
	letterSpacing12: '0.0025em',
	lineHeight12: '16px',
	fontSize14: '14px',
	letterSpacing14: '0',
	lineHeight14: '20px',
	fontSize16: '16px',
	letterSpacing16: '0',
	lineHeight16: '24px',
	fontSize18: '18px',
	letterSpacing18: '-0.0025em',
	lineHeight18: '26px',
	fontSize20: '20px',
	letterSpacing20: '-0.005em',
	lineHeight20: '28px',
	fontSize24: '24px',
	letterSpacing24: '-0.00625em',
	lineHeight24: '30px',
	fontSize28: '28px',
	letterSpacing28: '-0.0075em',
	lineHeight28: '36px',
	fontSize35: '35px',
	letterSpacing35: '-0.01em',
	lineHeight35: '40px',
	fontSize60: '60px',
	letterSpacing60: '-0.025em',
	lineHeight60: '60px',
});
