// Generated by scripts/generate-font-metric-consts.ts — do not edit.

import * as stylex from '@stylexjs/stylex';

/**
 * StyleX-importable mirror of `FONT_METRIC_SCALE` (`font-metric-scale.ts`), which stays the only
 * authored source — this file is NOT the source of truth. StyleX can only import values from a
 * `.stylex.ts` module, and `font-metric-scale.ts` must stay plain TypeScript so `build-themes.ts`
 * and `token-values.ts` can import it under `tsx` without a Babel step, so the scale is
 * flattened and mirrored here at generation time instead of imported directly.
 *
 * Keys are prefixed with `step` (e.g. `step12`, `step14`) rather than left as bare numbers,
 * because a numeric key would force bracket access (`fontMetrics[12].fontSize`) — the prefix
 * keeps every read plain dot notation, matching the authored scale's own metric-step vocabulary.
 */
export const fontMetrics = stylex.unstable_defineConstsNested({
	step12: {
		fontSize: '12px',
		letterSpacing: '0.0025em',
		lineHeight: '16px',
	},
	step14: {
		fontSize: '14px',
		letterSpacing: '0',
		lineHeight: '20px',
	},
	step16: {
		fontSize: '16px',
		letterSpacing: '0',
		lineHeight: '24px',
	},
	step18: {
		fontSize: '18px',
		letterSpacing: '-0.0025em',
		lineHeight: '26px',
	},
	step20: {
		fontSize: '20px',
		letterSpacing: '-0.005em',
		lineHeight: '28px',
	},
	step24: {
		fontSize: '24px',
		letterSpacing: '-0.00625em',
		lineHeight: '30px',
	},
	step28: {
		fontSize: '28px',
		letterSpacing: '-0.0075em',
		lineHeight: '36px',
	},
	step35: {
		fontSize: '35px',
		letterSpacing: '-0.01em',
		lineHeight: '40px',
	},
	step60: {
		fontSize: '60px',
		letterSpacing: '-0.025em',
		lineHeight: '60px',
	},
});
