/**
 * Writes the final CSS text from a theme's resolved identity and per-mode values. This is the
 * pipeline's last step, and it does no colour or contrast work: it formats contract pairs and the
 * values already resolved for them into the emitted stylesheet's rule blocks.
 */

import { precomputeValues } from '@capsizecss/vanilla-extract';
import { flattenThemeContract, fontSizeSteps, spaceScale } from './contract.js';
import type { ThemeFoundation } from './foundation.js';
import {
	codeFontFamilyStack,
	defaultFontFamily,
	defaultFontWeights,
	defaultRadius,
	themeFontFamilyStacks,
} from './foundation.js';
import { getThemeClassName } from './theme-class-name.js';
import {
	CONTROL_SIZE_VALUES,
	FONT_METRICS,
	FONT_VALUES,
	ICON_SIZE_VALUES,
	INTERACTION_VALUES,
	MOTION_VALUES,
} from './token-values.js';

type ColorMode = 'light' | 'dark';

/**
 * Emits the five rule blocks: an identity rule, the base light rule, the
 * `prefers-color-scheme: dark` media rule, and the two explicit `data-color-mode` rules. The
 * identity rule carries every non-mode contract leaf. Throws when a contract leaf has no resolved
 * value.
 */
export function assembleStylesheet(
	foundation: ThemeFoundation,
	lightValues: Record<string, string>,
	darkValues: Record<string, string>,
): string {
	const selector = `.${getThemeClassName(foundation.name)}`;
	const pairs = flattenThemeContract();
	const isModePath = (path: string) => {
		return (
			path.startsWith('actionControlFinish.') ||
			path.startsWith('color.') ||
			path.startsWith('depth.')
		);
	};
	const identityPairs = pairs.filter(([path]) => !isModePath(path));
	const modePairs = pairs.filter(([path]) => isModePath(path));

	const identityDeclarations = declarations(identityPairs, buildIdentityValues(foundation));
	const lightDeclarations = ['color-scheme: light;', ...declarations(modePairs, lightValues)];
	const darkDeclarations = ['color-scheme: dark;', ...declarations(modePairs, darkValues)];

	// Every rule pairs a `:where(:root)` fallback with the identity class, so one stylesheet themes
	// the whole document, including body-level portals. `:where()` zeroes the fallback's specificity
	// to (0,0,0), so an explicit identity always outranks another loaded theme's fallback, whatever
	// the stylesheet order. The explicit attribute rules are (0,2,0), so they beat the (0,1,0)
	// media-query rule wherever the attribute sits, whether on the theme root, inside its subtree,
	// or on an ancestor. Every scope sets native color-scheme, and the output is unlayered on purpose.
	const rootAndIdentitySelector = [':where(:root),', `${selector} {`];
	const attributeSelectors = (attributeMode: ColorMode) => {
		return [
			`:where(:root[data-color-mode='${attributeMode}']),`,
			`:where(:root) :where([data-color-mode='${attributeMode}']),`,
			`${selector}[data-color-mode='${attributeMode}'],`,
			`${selector} [data-color-mode='${attributeMode}'],`,
			`[data-color-mode='${attributeMode}'] ${selector} {`,
		].join('\n');
	};

	return [
		'/* Generated by buildTheme from @luke-ui/react. Do not edit. */',
		...rootAndIdentitySelector,
		...identityDeclarations.map(indent),
		'}',
		'',
		...rootAndIdentitySelector,
		...lightDeclarations.map(indent),
		'}',
		'',
		'@media (prefers-color-scheme: dark) {',
		...rootAndIdentitySelector.map(indent),
		...darkDeclarations.map(indent).map(indent),
		indent('}'),
		'}',
		'',
		attributeSelectors('light'),
		...lightDeclarations.map(indent),
		'}',
		'',
		attributeSelectors('dark'),
		...darkDeclarations.map(indent),
		'}',
		'',
	].join('\n');
}

function buildIdentityValues(foundation: ThemeFoundation): Record<string, string> {
	const fontFamily = foundation.typography?.fontFamily ?? defaultFontFamily;
	const fontWeight = foundation.typography?.fontWeight;
	const radius = foundation.radius;
	const values: Record<string, string> = {
		...CONTROL_SIZE_VALUES,
		...INTERACTION_VALUES,
		...FONT_VALUES,
		...buildCapsizeValues(fontFamily),
		'font.family.body': themeFontFamilyStacks[fontFamily],
		'font.family.code': codeFontFamilyStack,
		'font.weight.body': String(fontWeight?.body ?? defaultFontWeights.body),
		'font.weight.emphasis': String(fontWeight?.emphasis ?? defaultFontWeights.emphasis),
		'font.weight.heading': String(fontWeight?.heading ?? defaultFontWeights.heading),
		'font.weight.label': String(fontWeight?.label ?? defaultFontWeights.label),
		'radius.control': `${radius?.control ?? defaultRadius.control}px`,
		'radius.detail': `${radius?.detail ?? defaultRadius.detail}px`,
		'radius.full': '9999px',
		'radius.overlay': `${radius?.overlay ?? defaultRadius.overlay}px`,
		'radius.surface': `${radius?.surface ?? defaultRadius.surface}px`,
		...ICON_SIZE_VALUES,
		...MOTION_VALUES,
	};
	for (const [step, value] of spaceScale) {
		values[`space.${step}`] = value;
	}
	return values;
}

function buildCapsizeValues(fontFamily: keyof typeof FONT_METRICS): Record<string, string> {
	const values: Record<string, string> = {};
	for (const step of fontSizeSteps) {
		const fontSize = Number.parseFloat(FONT_VALUES[`font.${step}.fontSize`]);
		const leading = Number.parseFloat(FONT_VALUES[`font.${step}.lineHeight`]);
		const { baselineTrim, capHeightTrim } = precomputeValues({
			fontMetrics: FONT_METRICS[fontFamily],
			fontSize,
			leading,
		});
		values[`font.${step}.baselineTrim`] = baselineTrim;
		values[`font.${step}.capHeightTrim`] = capHeightTrim;
	}
	return values;
}

function declarations(
	pairs: Array<[path: string, varName: string]>,
	values: Record<string, string>,
): Array<string> {
	return pairs.map(([path, varName]) => {
		const value = values[path];
		if (value === undefined) throw new Error(`buildTheme did not generate a value for "${path}"`);
		return `${varName}: ${value};`;
	});
}

function indent(line: string): string {
	return `\t${line}`;
}
