/**
 * Writes the final CSS text from a theme's resolved identity and per-mode values. This is the
 * pipeline's last step, and it does no colour or contrast work: it formats contract pairs and the
 * values already resolved for them into the emitted stylesheet's rule blocks.
 */

import { precomputeValues } from '@capsizecss/core';
import { capsizeTrimVarName } from './capsize-trim-vars.js';
import type { IdentityPath, ModePath, SpaceStep } from './contract.js';
import { flattenThemeContract, partitionContractPairs, spaceScale } from './contract.js';
import { FONT_METRIC_SCALE } from './font-metric-scale.js';
import type { ThemeFont } from './font.js';
import type { ThemeFoundation } from './foundation.js';
import { codeFontFamilyStack, defaultFontWeights, defaultRadius } from './foundation.js';
import { pathEntry, pathRecord } from './path-record.js';
import { rem } from './rem.js';
import { getThemeClassName } from './theme-class-name.js';
import {
	CONTROL_SIZE_VALUES,
	FONT_VALUES,
	INTERACTION_VALUES,
	MOTION_VALUES,
} from './token-values.js';
import type { FontRole, TypeStyle } from './type-styles.js';
import {
	typeStyleFontRole,
	typeStyleMetricStep,
	typeStyles,
	typeStyleWeightRole,
} from './type-styles.js';

type ColorMode = 'light' | 'dark';

/**
 * Emits the five rule blocks, all scoped to the identity class on `<html>`: the theme-wide rule, the
 * base light rule, the `prefers-color-scheme: dark` media rule, and the two explicit
 * `data-color-mode` rules. The theme-wide rule carries every non-mode contract leaf, then the
 * private Capsize trims `Text` reads. Throws when a contract leaf has no resolved value.
 */
export function assembleStylesheet(
	foundation: ThemeFoundation,
	lightValues: Record<ModePath, string>,
	darkValues: Record<ModePath, string>,
): string {
	const { identityPairs, modePairs } = partitionContractPairs(flattenThemeContract());

	const themeWideDeclarations = [
		...declarations(identityPairs, buildIdentityValues(foundation)),
		...capsizeTrimDeclarations(foundation.typography.fonts),
	];
	const lightDeclarations = ['color-scheme: light;', ...declarations(modePairs, lightValues)];
	const darkDeclarations = ['color-scheme: dark;', ...declarations(modePairs, darkValues)];

	// The identity lives on `<html>` only. `:where(html)` keeps the base rules at (0,1,0), so the
	// explicit attribute rules, (0,2,0) whether the attribute sits on `<html>` or below it, beat the
	// media-query rule, and the nearest explicit scope wins by inheritance. The output is unlayered.
	const themeSelector = `:where(html).${getThemeClassName(foundation.name)}`;
	function explicitModeSelectors(mode: ColorMode) {
		return [
			`${themeSelector}[data-color-mode='${mode}'],`,
			`${themeSelector} [data-color-mode='${mode}'] {`,
		];
	}

	return [
		'/* Generated by defineTheme from @luke-ui/react. Do not edit. */',
		'',
		`${themeSelector} {`,
		...themeWideDeclarations.map(indent),
		'}',
		'',
		`${themeSelector} {`,
		...lightDeclarations.map(indent),
		'}',
		'',
		'@media (prefers-color-scheme: dark) {',
		indent(`${themeSelector} {`),
		...darkDeclarations.map(indent).map(indent),
		indent('}'),
		'}',
		'',
		...explicitModeSelectors('light'),
		...lightDeclarations.map(indent),
		'}',
		'',
		...explicitModeSelectors('dark'),
		...darkDeclarations.map(indent),
		'}',
		'',
	].join('\n');
}

function buildIdentityValues(foundation: ThemeFoundation): { [Path in IdentityPath]: string } {
	const { fontWeight } = foundation.typography;
	const radius = foundation.radius;
	const resolvedWeights = {
		body: String(fontWeight?.body ?? defaultFontWeights.body),
		emphasis: String(fontWeight?.emphasis ?? defaultFontWeights.emphasis),
		heading: String(fontWeight?.heading ?? defaultFontWeights.heading),
		label: String(fontWeight?.label ?? defaultFontWeights.label),
	};
	const fonts = resolveFontRoles(foundation.typography.fonts);
	return {
		...CONTROL_SIZE_VALUES,
		...INTERACTION_VALUES,
		...FONT_VALUES,
		...typeStyleValues('fontFamily', (style) => fonts[typeStyleFontRole[style]].family),
		...typeStyleValues('fontWeight', (style) => resolvedWeights[typeStyleWeightRole[style]]),
		'font.family.body': fonts.body.family,
		// A literal copy of the body family when there is no display font. A generated value never
		// references another token, so overriding one token never moves another.
		'font.family.display': fonts.display.family,
		'font.family.code': codeFontFamilyStack,
		'font.weight.body': resolvedWeights.body,
		'font.weight.emphasis': resolvedWeights.emphasis,
		'font.weight.heading': resolvedWeights.heading,
		'font.weight.label': resolvedWeights.label,
		'radius.control': rem(radius?.control ?? defaultRadius.control),
		'radius.detail': rem(radius?.detail ?? defaultRadius.detail),
		// Pill technique: a large fixed pixel radius, not scalable design geometry.
		'radius.full': '9999px',
		'radius.overlay': rem(radius?.overlay ?? defaultRadius.overlay),
		'radius.surface': rem(radius?.surface ?? defaultRadius.surface),
		...spaceValues(),
		...MOTION_VALUES,
	};
}

/** The font each role uses. A theme without a display font uses its body font for display. */
function resolveFontRoles(
	fonts: ThemeFoundation['typography']['fonts'],
): Record<FontRole, ThemeFont> {
	return { body: fonts.body, display: fonts.display ?? fonts.body };
}

function typeStyleValues<Field extends string>(
	field: Field,
	valueFor: (style: TypeStyle) => string,
): { [P in `font.${TypeStyle}.${Field}`]: string } {
	return pathRecord(
		typeStyles.map((style) => pathEntry(`font.${style}.${field}`, valueFor(style))),
	);
}

function spaceValues(): { [Step in SpaceStep as `space.${Step}`]: string } {
	return pathRecord(spaceScale.map(([step, value]) => pathEntry(`space.${step}`, value)));
}

/**
 * The private `--luke-internal-*` Capsize trim declarations for every type style, each from the
 * metrics of the font its role uses.
 */
function capsizeTrimDeclarations(fonts: ThemeFoundation['typography']['fonts']): Array<string> {
	const roles = resolveFontRoles(fonts);
	return typeStyles.flatMap((style) => {
		const { baselineTrim, capHeightTrim } = capsizeTrims(roles[typeStyleFontRole[style]], style);
		return [
			`${capsizeTrimVarName(style, 'baselineTrim')}: ${baselineTrim};`,
			`${capsizeTrimVarName(style, 'capHeightTrim')}: ${capHeightTrim};`,
		];
	});
}

function capsizeTrims(font: ThemeFont, style: TypeStyle) {
	// Capsize expects pixel numbers. Metric keys match the 16px root, so trims stay correct when CSS
	// emits rem.
	const fontSize = typeStyleMetricStep[style];
	const leading = Number.parseFloat(FONT_METRIC_SCALE[fontSize].lineHeight) * 16;
	return precomputeValues({ fontMetrics: font.metrics, fontSize, leading });
}

function declarations<Path extends string>(
	pairs: Array<[Path, string]>,
	values: Record<Path, string>,
): Array<string> {
	return pairs.map(([path, varName]) => {
		const value = values[path];
		if (value === undefined) throw new Error(`buildTheme did not generate a value for "${path}"`);
		return `${varName}: ${value};`;
	});
}

function indent(line: string): string {
	return `\t${line}`;
}
