/**
 * Writes the final CSS text from a theme's resolved identity and per-mode values. This is the
 * pipeline's last step, and it does no colour or contrast work: it formats contract pairs and the
 * values already resolved for them into the emitted stylesheet's rule blocks.
 */

import { precomputeValues } from '@capsizecss/vanilla-extract';
import {
	flattenThemeContract,
	partitionContractPairs,
	spaceScale,
	typeStyleWeightRole,
} from './contract.js';
import type { IdentityPath, ModePath, SpaceStep, TypeStyle } from './contract.js';
import type { ThemeFoundation } from './foundation.js';
import {
	codeFontFamilyStack,
	defaultFontFamily,
	defaultFontWeights,
	defaultRadius,
	themeFontFamilyStacks,
} from './foundation.js';
import { getThemeClassName } from './theme-class-name.js';
import {
	CONTROL_SIZE_VALUES,
	FONT_METRICS,
	FONT_VALUES,
	ICON_SIZE_VALUES,
	INTERACTION_VALUES,
	MOTION_VALUES,
} from './token-values.js';

type ColorMode = 'light' | 'dark';

/**
 * Emits the five rule blocks: an identity rule, the base light rule, the
 * `prefers-color-scheme: dark` media rule, and the two explicit `data-color-mode` rules. The
 * identity rule carries every non-mode contract leaf. Throws when a contract leaf has no resolved
 * value.
 */
export function assembleStylesheet(
	foundation: ThemeFoundation,
	lightValues: Record<ModePath, string>,
	darkValues: Record<ModePath, string>,
): string {
	const selector = `.${getThemeClassName(foundation.name)}`;
	const { identityPairs, modePairs } = partitionContractPairs(flattenThemeContract());

	const identityDeclarations = declarations(identityPairs, buildIdentityValues(foundation));
	const lightDeclarations = ['color-scheme: light;', ...declarations(modePairs, lightValues)];
	const darkDeclarations = ['color-scheme: dark;', ...declarations(modePairs, darkValues)];

	// Every rule pairs a `:where(:root)` fallback with the identity class, so one stylesheet themes
	// the whole document, including body-level portals. `:where()` zeroes the fallback's specificity
	// to (0,0,0), so an explicit identity always outranks another loaded theme's fallback, whatever
	// the stylesheet order. The explicit attribute rules are (0,2,0), so they beat the (0,1,0)
	// media-query rule wherever the attribute sits, whether on the theme root, inside its subtree,
	// or on an ancestor. Every scope sets native color-scheme, and the output is unlayered on purpose.
	const rootAndIdentitySelector = [':where(:root),', `${selector} {`];
	const attributeSelectors = (attributeMode: ColorMode) => {
		return [
			`:where(:root[data-color-mode='${attributeMode}']),`,
			`:where(:root) :where([data-color-mode='${attributeMode}']),`,
			`${selector}[data-color-mode='${attributeMode}'],`,
			`${selector} [data-color-mode='${attributeMode}'],`,
			`[data-color-mode='${attributeMode}'] ${selector} {`,
		].join('\n');
	};

	return [
		'/* Generated by buildTheme from @luke-ui/react. Do not edit. */',
		...rootAndIdentitySelector,
		...identityDeclarations.map(indent),
		'}',
		'',
		...rootAndIdentitySelector,
		...lightDeclarations.map(indent),
		'}',
		'',
		'@media (prefers-color-scheme: dark) {',
		...rootAndIdentitySelector.map(indent),
		...darkDeclarations.map(indent).map(indent),
		indent('}'),
		'}',
		'',
		attributeSelectors('light'),
		...lightDeclarations.map(indent),
		'}',
		'',
		attributeSelectors('dark'),
		...darkDeclarations.map(indent),
		'}',
		'',
	].join('\n');
}

function buildIdentityValues(foundation: ThemeFoundation): { [Path in IdentityPath]: string } {
	const fontFamily = foundation.typography?.fontFamily ?? defaultFontFamily;
	const fontWeight = foundation.typography?.fontWeight;
	const radius = foundation.radius;
	const resolvedWeights = {
		body: String(fontWeight?.body ?? defaultFontWeights.body),
		emphasis: String(fontWeight?.emphasis ?? defaultFontWeights.emphasis),
		heading: String(fontWeight?.heading ?? defaultFontWeights.heading),
		label: String(fontWeight?.label ?? defaultFontWeights.label),
	};
	const bodyFontFamily = themeFontFamilyStacks[fontFamily];
	return {
		...CONTROL_SIZE_VALUES,
		...INTERACTION_VALUES,
		...FONT_VALUES,
		...buildCapsizeValues(fontFamily),
		...typeStyleFontFamilies(bodyFontFamily),
		...typeStyleFontWeights(resolvedWeights),
		'font.family.body': bodyFontFamily,
		'font.family.code': codeFontFamilyStack,
		'font.weight.body': resolvedWeights.body,
		'font.weight.emphasis': resolvedWeights.emphasis,
		'font.weight.heading': resolvedWeights.heading,
		'font.weight.label': resolvedWeights.label,
		'radius.control': `${radius?.control ?? defaultRadius.control}px`,
		'radius.detail': `${radius?.detail ?? defaultRadius.detail}px`,
		'radius.full': '9999px',
		'radius.overlay': `${radius?.overlay ?? defaultRadius.overlay}px`,
		'radius.surface': `${radius?.surface ?? defaultRadius.surface}px`,
		...spaceValues(),
		...ICON_SIZE_VALUES,
		...MOTION_VALUES,
	};
}

function typeStyleFontFamilies(family: string): {
	[Style in TypeStyle as `font.${Style}.fontFamily`]: string;
} {
	return {
		'font.body.fontFamily': family,
		'font.caption.fontFamily': family,
		'font.display.fontFamily': family,
		'font.heading1.fontFamily': family,
		'font.heading2.fontFamily': family,
		'font.heading3.fontFamily': family,
		'font.heading4.fontFamily': family,
		'font.label.fontFamily': family,
		'font.lead.fontFamily': family,
		'font.support.fontFamily': family,
	};
}

function typeStyleFontWeights(weights: {
	body: string;
	emphasis: string;
	heading: string;
	label: string;
}): { [Style in TypeStyle as `font.${Style}.fontWeight`]: string } {
	return {
		'font.body.fontWeight': weights[typeStyleWeightRole.body],
		'font.caption.fontWeight': weights[typeStyleWeightRole.caption],
		'font.display.fontWeight': weights[typeStyleWeightRole.display],
		'font.heading1.fontWeight': weights[typeStyleWeightRole.heading1],
		'font.heading2.fontWeight': weights[typeStyleWeightRole.heading2],
		'font.heading3.fontWeight': weights[typeStyleWeightRole.heading3],
		'font.heading4.fontWeight': weights[typeStyleWeightRole.heading4],
		'font.label.fontWeight': weights[typeStyleWeightRole.label],
		'font.lead.fontWeight': weights[typeStyleWeightRole.lead],
		'font.support.fontWeight': weights[typeStyleWeightRole.support],
	};
}

function spaceValues(): { [Step in SpaceStep as `space.${Step}`]: string } {
	return {
		'space.100': spaceStep('100'),
		'space.1000': spaceStep('1000'),
		'space.1200': spaceStep('1200'),
		'space.1600': spaceStep('1600'),
		'space.200': spaceStep('200'),
		'space.300': spaceStep('300'),
		'space.400': spaceStep('400'),
		'space.600': spaceStep('600'),
		'space.800': spaceStep('800'),
	};
}

function spaceStep(step: SpaceStep): string {
	for (const [key, value] of spaceScale) {
		if (key === step) return value;
	}
	throw new Error(`spaceScale is missing "${step}"`);
}

function buildCapsizeValues(fontFamily: keyof typeof FONT_METRICS): {
	[Style in TypeStyle as `font.${Style}.baselineTrim`]: string;
} & {
	[Style in TypeStyle as `font.${Style}.capHeightTrim`]: string;
} {
	const caption = capsizeTrims(fontFamily, 'caption');
	const support = capsizeTrims(fontFamily, 'support');
	const label = capsizeTrims(fontFamily, 'label');
	const body = capsizeTrims(fontFamily, 'body');
	const lead = capsizeTrims(fontFamily, 'lead');
	const heading4 = capsizeTrims(fontFamily, 'heading4');
	const heading3 = capsizeTrims(fontFamily, 'heading3');
	const heading2 = capsizeTrims(fontFamily, 'heading2');
	const heading1 = capsizeTrims(fontFamily, 'heading1');
	const display = capsizeTrims(fontFamily, 'display');
	return {
		'font.body.baselineTrim': body.baselineTrim,
		'font.body.capHeightTrim': body.capHeightTrim,
		'font.caption.baselineTrim': caption.baselineTrim,
		'font.caption.capHeightTrim': caption.capHeightTrim,
		'font.display.baselineTrim': display.baselineTrim,
		'font.display.capHeightTrim': display.capHeightTrim,
		'font.heading1.baselineTrim': heading1.baselineTrim,
		'font.heading1.capHeightTrim': heading1.capHeightTrim,
		'font.heading2.baselineTrim': heading2.baselineTrim,
		'font.heading2.capHeightTrim': heading2.capHeightTrim,
		'font.heading3.baselineTrim': heading3.baselineTrim,
		'font.heading3.capHeightTrim': heading3.capHeightTrim,
		'font.heading4.baselineTrim': heading4.baselineTrim,
		'font.heading4.capHeightTrim': heading4.capHeightTrim,
		'font.label.baselineTrim': label.baselineTrim,
		'font.label.capHeightTrim': label.capHeightTrim,
		'font.lead.baselineTrim': lead.baselineTrim,
		'font.lead.capHeightTrim': lead.capHeightTrim,
		'font.support.baselineTrim': support.baselineTrim,
		'font.support.capHeightTrim': support.capHeightTrim,
	};
}

function capsizeTrims(fontFamily: keyof typeof FONT_METRICS, style: TypeStyle) {
	const fontSize = Number.parseFloat(FONT_VALUES[`font.${style}.fontSize`]);
	const leading = Number.parseFloat(FONT_VALUES[`font.${style}.lineHeight`]);
	return precomputeValues({
		fontMetrics: FONT_METRICS[fontFamily],
		fontSize,
		leading,
	});
}

function declarations<Path extends string>(
	pairs: Array<[Path, string]>,
	values: Record<Path, string>,
): Array<string> {
	return pairs.map(([path, varName]) => {
		const value = values[path];
		if (value === undefined) throw new Error(`buildTheme did not generate a value for "${path}"`);
		return `${varName}: ${value};`;
	});
}

function indent(line: string): string {
	return `\t${line}`;
}
