// Generated by scripts/generate-stylex-tokens.ts — do not edit.

import * as stylex from '@stylexjs/stylex';

/**
 * The one theme token interface: nested paths such as `vars.color.background.danger.solid.hover`
 * mirror the theme contract tree exactly. Each leaf is a live `var(--luke-*)` reference. Used by
 * StyleX recipes, remaining Vanilla Extract styles, and re-exported as the public
 * `@luke-ui/react/theme` `vars`.
 */
export const vars = stylex.unstable_defineConstsNested({
	color: {
		surface: {
			canvas: 'var(--luke-color-surface-canvas)',
			recessed: 'var(--luke-color-surface-recessed)',
			floating: 'var(--luke-color-surface-floating)',
			overlay: 'var(--luke-color-surface-overlay)',
		},
		overlay: {
			backdrop: 'var(--luke-color-overlay-backdrop)',
		},
		loadingSkeleton: 'var(--luke-color-loading-skeleton)',
		text: {
			primary: 'var(--luke-color-text-primary)',
			secondary: 'var(--luke-color-text-secondary)',
			disabled: 'var(--luke-color-text-disabled)',
		},
		background: {
			neutral: {
				subtle: {
					rest: 'var(--luke-color-background-neutral-subtle-rest)',
					hover: 'var(--luke-color-background-neutral-subtle-hover)',
					pressed: 'var(--luke-color-background-neutral-subtle-pressed)',
				},
				solid: {
					rest: 'var(--luke-color-background-neutral-solid-rest)',
					hover: 'var(--luke-color-background-neutral-solid-hover)',
					pressed: 'var(--luke-color-background-neutral-solid-pressed)',
				},
			},
			accent: {
				subtle: {
					rest: 'var(--luke-color-background-accent-subtle-rest)',
					hover: 'var(--luke-color-background-accent-subtle-hover)',
					pressed: 'var(--luke-color-background-accent-subtle-pressed)',
				},
				solid: {
					rest: 'var(--luke-color-background-accent-solid-rest)',
					hover: 'var(--luke-color-background-accent-solid-hover)',
					pressed: 'var(--luke-color-background-accent-solid-pressed)',
				},
			},
			info: {
				subtle: {
					rest: 'var(--luke-color-background-info-subtle-rest)',
					hover: 'var(--luke-color-background-info-subtle-hover)',
					pressed: 'var(--luke-color-background-info-subtle-pressed)',
				},
				solid: {
					rest: 'var(--luke-color-background-info-solid-rest)',
					hover: 'var(--luke-color-background-info-solid-hover)',
					pressed: 'var(--luke-color-background-info-solid-pressed)',
				},
			},
			success: {
				subtle: {
					rest: 'var(--luke-color-background-success-subtle-rest)',
					hover: 'var(--luke-color-background-success-subtle-hover)',
					pressed: 'var(--luke-color-background-success-subtle-pressed)',
				},
				solid: {
					rest: 'var(--luke-color-background-success-solid-rest)',
					hover: 'var(--luke-color-background-success-solid-hover)',
					pressed: 'var(--luke-color-background-success-solid-pressed)',
				},
			},
			warning: {
				subtle: {
					rest: 'var(--luke-color-background-warning-subtle-rest)',
					hover: 'var(--luke-color-background-warning-subtle-hover)',
					pressed: 'var(--luke-color-background-warning-subtle-pressed)',
				},
				solid: {
					rest: 'var(--luke-color-background-warning-solid-rest)',
					hover: 'var(--luke-color-background-warning-solid-hover)',
					pressed: 'var(--luke-color-background-warning-solid-pressed)',
				},
			},
			danger: {
				subtle: {
					rest: 'var(--luke-color-background-danger-subtle-rest)',
					hover: 'var(--luke-color-background-danger-subtle-hover)',
					pressed: 'var(--luke-color-background-danger-subtle-pressed)',
				},
				solid: {
					rest: 'var(--luke-color-background-danger-solid-rest)',
					hover: 'var(--luke-color-background-danger-solid-hover)',
					pressed: 'var(--luke-color-background-danger-solid-pressed)',
				},
			},
		},
		foreground: {
			neutral: {
				rest: 'var(--luke-color-foreground-neutral-rest)',
				hover: 'var(--luke-color-foreground-neutral-hover)',
				pressed: 'var(--luke-color-foreground-neutral-pressed)',
				onSolid: 'var(--luke-color-foreground-neutral-on-solid)',
			},
			accent: {
				rest: 'var(--luke-color-foreground-accent-rest)',
				hover: 'var(--luke-color-foreground-accent-hover)',
				pressed: 'var(--luke-color-foreground-accent-pressed)',
				onSolid: 'var(--luke-color-foreground-accent-on-solid)',
			},
			info: {
				rest: 'var(--luke-color-foreground-info-rest)',
				hover: 'var(--luke-color-foreground-info-hover)',
				pressed: 'var(--luke-color-foreground-info-pressed)',
				onSolid: 'var(--luke-color-foreground-info-on-solid)',
			},
			success: {
				rest: 'var(--luke-color-foreground-success-rest)',
				hover: 'var(--luke-color-foreground-success-hover)',
				pressed: 'var(--luke-color-foreground-success-pressed)',
				onSolid: 'var(--luke-color-foreground-success-on-solid)',
			},
			warning: {
				rest: 'var(--luke-color-foreground-warning-rest)',
				hover: 'var(--luke-color-foreground-warning-hover)',
				pressed: 'var(--luke-color-foreground-warning-pressed)',
				onSolid: 'var(--luke-color-foreground-warning-on-solid)',
			},
			danger: {
				rest: 'var(--luke-color-foreground-danger-rest)',
				hover: 'var(--luke-color-foreground-danger-hover)',
				pressed: 'var(--luke-color-foreground-danger-pressed)',
				onSolid: 'var(--luke-color-foreground-danger-on-solid)',
			},
		},
		border: {
			decorative: 'var(--luke-color-border-decorative)',
			control: 'var(--luke-color-border-control)',
			focus: 'var(--luke-color-border-focus)',
			neutral: 'var(--luke-color-border-neutral)',
			accent: 'var(--luke-color-border-accent)',
			info: 'var(--luke-color-border-info)',
			success: 'var(--luke-color-border-success)',
			warning: 'var(--luke-color-border-warning)',
			danger: 'var(--luke-color-border-danger)',
		},
	},
	depth: {
		recessed: 'var(--luke-depth-recessed)',
		resting: 'var(--luke-depth-resting)',
		raised: 'var(--luke-depth-raised)',
		floating: 'var(--luke-depth-floating)',
		overlay: 'var(--luke-depth-overlay)',
	},
	actionControlFinish: {
		recessed: 'var(--luke-action-control-finish-recessed)',
		resting: 'var(--luke-action-control-finish-resting)',
		raised: 'var(--luke-action-control-finish-raised)',
	},
	font: {
		caption: {
			baselineTrim: 'var(--luke-font-caption-baseline-trim)',
			capHeightTrim: 'var(--luke-font-caption-cap-height-trim)',
			fontFamily: 'var(--luke-font-caption-font-family)',
			fontSize: 'var(--luke-font-caption-font-size)',
			fontWeight: 'var(--luke-font-caption-font-weight)',
			letterSpacing: 'var(--luke-font-caption-letter-spacing)',
			lineHeight: 'var(--luke-font-caption-line-height)',
		},
		label: {
			baselineTrim: 'var(--luke-font-label-baseline-trim)',
			capHeightTrim: 'var(--luke-font-label-cap-height-trim)',
			fontFamily: 'var(--luke-font-label-font-family)',
			fontSize: 'var(--luke-font-label-font-size)',
			fontWeight: 'var(--luke-font-label-font-weight)',
			letterSpacing: 'var(--luke-font-label-letter-spacing)',
			lineHeight: 'var(--luke-font-label-line-height)',
		},
		body: {
			baselineTrim: 'var(--luke-font-body-baseline-trim)',
			capHeightTrim: 'var(--luke-font-body-cap-height-trim)',
			fontFamily: 'var(--luke-font-body-font-family)',
			fontSize: 'var(--luke-font-body-font-size)',
			fontWeight: 'var(--luke-font-body-font-weight)',
			letterSpacing: 'var(--luke-font-body-letter-spacing)',
			lineHeight: 'var(--luke-font-body-line-height)',
		},
		lead: {
			baselineTrim: 'var(--luke-font-lead-baseline-trim)',
			capHeightTrim: 'var(--luke-font-lead-cap-height-trim)',
			fontFamily: 'var(--luke-font-lead-font-family)',
			fontSize: 'var(--luke-font-lead-font-size)',
			fontWeight: 'var(--luke-font-lead-font-weight)',
			letterSpacing: 'var(--luke-font-lead-letter-spacing)',
			lineHeight: 'var(--luke-font-lead-line-height)',
		},
		heading4: {
			baselineTrim: 'var(--luke-font-heading4-baseline-trim)',
			capHeightTrim: 'var(--luke-font-heading4-cap-height-trim)',
			fontFamily: 'var(--luke-font-heading4-font-family)',
			fontSize: 'var(--luke-font-heading4-font-size)',
			fontWeight: 'var(--luke-font-heading4-font-weight)',
			letterSpacing: 'var(--luke-font-heading4-letter-spacing)',
			lineHeight: 'var(--luke-font-heading4-line-height)',
		},
		heading3: {
			baselineTrim: 'var(--luke-font-heading3-baseline-trim)',
			capHeightTrim: 'var(--luke-font-heading3-cap-height-trim)',
			fontFamily: 'var(--luke-font-heading3-font-family)',
			fontSize: 'var(--luke-font-heading3-font-size)',
			fontWeight: 'var(--luke-font-heading3-font-weight)',
			letterSpacing: 'var(--luke-font-heading3-letter-spacing)',
			lineHeight: 'var(--luke-font-heading3-line-height)',
		},
		heading2: {
			baselineTrim: 'var(--luke-font-heading2-baseline-trim)',
			capHeightTrim: 'var(--luke-font-heading2-cap-height-trim)',
			fontFamily: 'var(--luke-font-heading2-font-family)',
			fontSize: 'var(--luke-font-heading2-font-size)',
			fontWeight: 'var(--luke-font-heading2-font-weight)',
			letterSpacing: 'var(--luke-font-heading2-letter-spacing)',
			lineHeight: 'var(--luke-font-heading2-line-height)',
		},
		heading1: {
			baselineTrim: 'var(--luke-font-heading1-baseline-trim)',
			capHeightTrim: 'var(--luke-font-heading1-cap-height-trim)',
			fontFamily: 'var(--luke-font-heading1-font-family)',
			fontSize: 'var(--luke-font-heading1-font-size)',
			fontWeight: 'var(--luke-font-heading1-font-weight)',
			letterSpacing: 'var(--luke-font-heading1-letter-spacing)',
			lineHeight: 'var(--luke-font-heading1-line-height)',
		},
		display: {
			baselineTrim: 'var(--luke-font-display-baseline-trim)',
			capHeightTrim: 'var(--luke-font-display-cap-height-trim)',
			fontFamily: 'var(--luke-font-display-font-family)',
			fontSize: 'var(--luke-font-display-font-size)',
			fontWeight: 'var(--luke-font-display-font-weight)',
			letterSpacing: 'var(--luke-font-display-letter-spacing)',
			lineHeight: 'var(--luke-font-display-line-height)',
		},
		family: {
			body: 'var(--luke-font-family-body)',
			code: 'var(--luke-font-family-code)',
		},
		weight: {
			body: 'var(--luke-font-weight-body)',
			label: 'var(--luke-font-weight-label)',
			heading: 'var(--luke-font-weight-heading)',
			emphasis: 'var(--luke-font-weight-emphasis)',
		},
	},
	radius: {
		detail: 'var(--luke-radius-detail)',
		control: 'var(--luke-radius-control)',
		surface: 'var(--luke-radius-surface)',
		overlay: 'var(--luke-radius-overlay)',
		full: 'var(--luke-radius-full)',
	},
	space: {
		sp4: 'var(--luke-space-sp4)',
		sp8: 'var(--luke-space-sp8)',
		sp12: 'var(--luke-space-sp12)',
		sp16: 'var(--luke-space-sp16)',
		sp24: 'var(--luke-space-sp24)',
		sp32: 'var(--luke-space-sp32)',
		sp40: 'var(--luke-space-sp40)',
		sp48: 'var(--luke-space-sp48)',
		sp64: 'var(--luke-space-sp64)',
	},
	controlSize: {
		small: 'var(--luke-control-size-small)',
		medium: 'var(--luke-control-size-medium)',
		minTarget: 'var(--luke-control-size-min-target)',
		comboboxAction: 'var(--luke-control-size-combobox-action)',
	},
	interaction: {
		disabledOpacity: 'var(--luke-interaction-disabled-opacity)',
	},
	iconSize: {
		xsmall: 'var(--luke-icon-size-xsmall)',
		small: 'var(--luke-icon-size-small)',
		medium: 'var(--luke-icon-size-medium)',
		large: 'var(--luke-icon-size-large)',
	},
	motion: {
		duration: {
			feedback: 'var(--luke-motion-duration-feedback)',
			enter: 'var(--luke-motion-duration-enter)',
			exit: 'var(--luke-motion-duration-exit)',
		},
		easing: {
			standard: 'var(--luke-motion-easing-standard)',
			exit: 'var(--luke-motion-easing-exit)',
		},
	},
});
