import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { expect, test } from 'vite-plus/test';
import { parseComponentFrontmatter, renderPropsPage } from '../../scripts/generate-props-pages.js';

const componentsDir = resolve(import.meta.dirname, '../../content/docs/components');

test('renders a single-entry Props page with no sub-headings', () => {
	const frontmatter = parseComponentFrontmatter(`---
title: Button
description: A labelled control for actions in an interface.
source: packages/@luke-ui/react/src/button
reactAria: https://react-spectrum.adobe.com/react-aria/Button.html
props:
  - name: ButtonProps
    path: packages/@luke-ui/react/src/button/index.tsx
---
`);

	expect(renderPropsPage(frontmatter)).toBe(`---
title: Button
description: A labelled control for actions in an interface.
source: packages/@luke-ui/react/src/button
reactAria: https://react-spectrum.adobe.com/react-aria/Button.html
---

{/* Generated by scripts/generate-props-pages.ts — do not edit. */}

## Props

<auto-type-table path="packages/@luke-ui/react/src/button/index.tsx" name="ButtonProps" />
`);
});

test('renders a multi-entry Props page with a heading per entry', () => {
	const frontmatter = parseComponentFrontmatter(`---
title: Field primitive
description: Shared label, description, and validation parts for custom fields.
source: packages/@luke-ui/react/src/field/primitive
props:
  - name: FieldProps
    path: packages/@luke-ui/react/src/field/primitive/index.tsx
    heading: Field
  - name: FieldLabelProps
    path: packages/@luke-ui/react/src/field/primitive/label.tsx
    heading: FieldLabel
---
`);

	expect(renderPropsPage(frontmatter)).toBe(`---
title: Field primitive
description: Shared label, description, and validation parts for custom fields.
source: packages/@luke-ui/react/src/field/primitive
---

{/* Generated by scripts/generate-props-pages.ts — do not edit. */}

## Props

### Field

<auto-type-table path="packages/@luke-ui/react/src/field/primitive/index.tsx" name="FieldProps" />

### FieldLabel

<auto-type-table
	path="packages/@luke-ui/react/src/field/primitive/label.tsx"
	name="FieldLabelProps"
/>
`);
});

test('every component index.mdx declaring props has a generated Props page on disk', () => {
	for (const group of readdirSync(componentsDir, { withFileTypes: true })) {
		if (!group.isDirectory()) continue;
		const groupDir = resolve(componentsDir, group.name);

		for (const component of readdirSync(groupDir, { withFileTypes: true })) {
			if (!component.isDirectory()) continue;
			const componentDir = resolve(groupDir, component.name);
			const indexPath = resolve(componentDir, 'index.mdx');
			if (!existsSync(indexPath)) continue;

			const frontmatter = parseComponentFrontmatter(readFileSync(indexPath, 'utf8'));
			if (frontmatter.props.length === 0) continue;

			const relativeComponentDir = `${group.name}/${component.name}`;
			const propsPath = resolve(componentDir, 'props.mdx');
			const metaPath = resolve(componentDir, 'meta.json');

			expect(existsSync(propsPath), `${relativeComponentDir}/props.mdx should exist`).toBe(true);
			expect(existsSync(metaPath), `${relativeComponentDir}/meta.json should exist`).toBe(true);
			expect(readFileSync(propsPath, 'utf8')).toBe(renderPropsPage(frontmatter));
		}
	}
});
