import {
	existsSync,
	mkdirSync,
	mkdtempSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { afterEach, expect, test } from 'vite-plus/test';
import {
	generatePropsPages,
	parseComponentFrontmatter,
	renderPropsPage,
} from '../../scripts/generate-props-pages.js';

const componentsDir = resolve(import.meta.dirname, '../../content/docs/components');

test('renders a single-entry Props page with no sub-headings', () => {
	const frontmatter = parseComponentFrontmatter(`---
title: Button
description: A labelled control for actions in an interface.
source: packages/@luke-ui/react/src/button
reactAria: https://react-spectrum.adobe.com/react-aria/Button.html
props:
  - name: ButtonProps
    path: packages/@luke-ui/react/src/button/index.tsx
---
`);

	expect(renderPropsPage(frontmatter)).toBe(`---
title: Button
description: A labelled control for actions in an interface.
source: packages/@luke-ui/react/src/button
reactAria: https://react-spectrum.adobe.com/react-aria/Button.html
---

{/* Generated by scripts/generate-props-pages.ts. Do not edit. */}

## Props

<auto-type-table path="packages/@luke-ui/react/src/button/index.tsx" name="ButtonProps" />
`);
});

test('renders a multi-entry Props page with a heading per entry', () => {
	const frontmatter = parseComponentFrontmatter(`---
title: Field primitive
description: Shared label, description, and validation parts for custom fields.
source: packages/@luke-ui/react/src/field/primitive
props:
  - name: FieldProps
    path: packages/@luke-ui/react/src/field/primitive/index.tsx
    heading: Field
  - name: FieldLabelProps
    path: packages/@luke-ui/react/src/field/primitive/label.tsx
    heading: FieldLabel
---
`);

	expect(renderPropsPage(frontmatter)).toBe(`---
title: Field primitive
description: Shared label, description, and validation parts for custom fields.
source: packages/@luke-ui/react/src/field/primitive
---

{/* Generated by scripts/generate-props-pages.ts. Do not edit. */}

## Props

### Field

<auto-type-table path="packages/@luke-ui/react/src/field/primitive/index.tsx" name="FieldProps" />

### FieldLabel

<auto-type-table
	path="packages/@luke-ui/react/src/field/primitive/label.tsx"
	name="FieldLabelProps"
/>
`);
});

test('every component index.mdx declaring props has a generated Props page on disk', () => {
	for (const group of readdirSync(componentsDir, { withFileTypes: true })) {
		if (!group.isDirectory()) continue;
		const groupDir = resolve(componentsDir, group.name);

		for (const component of readdirSync(groupDir, { withFileTypes: true })) {
			if (!component.isDirectory()) continue;
			const componentDir = resolve(groupDir, component.name);
			const indexPath = resolve(componentDir, 'index.mdx');
			if (!existsSync(indexPath)) continue;

			const frontmatter = parseComponentFrontmatter(readFileSync(indexPath, 'utf8'));
			if (frontmatter.props.length === 0) continue;

			const relativeComponentDir = `${group.name}/${component.name}`;
			const propsPath = resolve(componentDir, 'props.mdx');
			const metaPath = resolve(componentDir, 'meta.json');

			expect(existsSync(propsPath), `${relativeComponentDir}/props.mdx should exist`).toBe(true);
			expect(existsSync(metaPath), `${relativeComponentDir}/meta.json should exist`).toBe(true);
			expect(readFileSync(propsPath, 'utf8')).toBe(renderPropsPage(frontmatter));
		}
	}
});

let scratchDir: string | undefined;

afterEach(() => {
	if (scratchDir !== undefined) rmSync(scratchDir, { force: true, recursive: true });
	scratchDir = undefined;
});

function writeScratchComponent(indexContents: string): {
	metaPath: string;
	propsPath: string;
	rootDir: string;
} {
	scratchDir = mkdtempSync(resolve(tmpdir(), 'luke-ui-props-'));
	const componentDir = resolve(scratchDir, 'actions/button');
	mkdirSync(componentDir, { recursive: true });
	writeFileSync(resolve(componentDir, 'index.mdx'), indexContents);
	return {
		metaPath: resolve(componentDir, 'meta.json'),
		propsPath: resolve(componentDir, 'props.mdx'),
		rootDir: scratchDir,
	};
}

const SCRATCH_INDEX = `---
title: Button
props:
  - name: ButtonProps
    path: packages/@luke-ui/react/src/button/index.tsx
---

Guide body.
`;

test('removes generated output for a component whose index.mdx has gone', () => {
	const { metaPath, propsPath, rootDir } = writeScratchComponent(SCRATCH_INDEX);

	expect(generatePropsPages(rootDir)).toEqual({ componentCount: 1, removedCount: 0 });
	expect(existsSync(propsPath)).toBe(true);
	expect(existsSync(metaPath)).toBe(true);

	// Deleting or renaming the guide must not leave an orphaned Props page behind. It would keep
	// serving stale content from a route that is gitignored, so review would never surface it.
	rmSync(resolve(rootDir, 'actions/button/index.mdx'));

	expect(generatePropsPages(rootDir)).toEqual({ componentCount: 0, removedCount: 2 });
	expect(existsSync(propsPath)).toBe(false);
	expect(existsSync(metaPath)).toBe(false);
});
