/** Stable key for curated taught-prop metadata: `path::name`. */
export function tableKey(path: string, name: string): string {
	return `${path}::${name}`;
}

/**
 * Props each authored API table explicitly teaches as intentional Luke UI behaviour. Keys match
 * `<component-props-table>` tags parsed from guides. An empty array means the table documents a
 * type that teaches no named Luke UI contract props beyond native DOM pass-through.
 */
export const GUIDE_TAUGHT_PROPS: Readonly<Record<string, ReadonlyArray<string>>> = {
	'packages/@luke-ui/react/src/core/blockquote/blockquote.tsx::BlockquoteProps': [
		'fontWeight',
		'lineClamp',
		'typography',
	],
	'packages/@luke-ui/react/src/core/box/box.tsx::BoxProps': ['elementType', 'ref', 'render'],
	'packages/@luke-ui/react/src/core/button/button.tsx::ButtonProps': [
		'appearance',
		'isBlock',
		'isDisabled',
		'isPending',
		'size',
		'startIcon',
		'endIcon',
		'tone',
	],
	'packages/@luke-ui/react/src/core/checkbox/checkbox.tsx::CheckboxProps': [
		'defaultSelected',
		'description',
		'errorMessage',
		'inputRef',
		'isDisabled',
		'isIndeterminate',
		'isReadOnly',
		'isRequired',
		'isSelected',
		'onChange',
		'size',
	],
	'packages/@luke-ui/react/src/core/code/code.tsx::CodeProps': [],
	'packages/@luke-ui/react/src/core/combobox-field/combobox-field.tsx::ComboboxFieldProps': [
		'defaultItems',
		'errorMessage',
		'inputRef',
		'isRequired',
		'items',
		'label',
		'listBoxProps',
		'loadMoreItem',
		'loadingState',
		'menuWidth',
		'name',
		'necessityIndicator',
		'onLoadMore',
		'placeholder',
		'popoverProps',
		'size',
		'validate',
	],
	'packages/@luke-ui/react/src/core/em/em.tsx::EmProps': ['lineClamp', 'textWrap'],
	'packages/@luke-ui/react/src/core/emoji/emoji.tsx::EmojiProps': ['emoji', 'label'],
	'packages/@luke-ui/react/src/core/heading/heading-context.tsx::HeadingLevelsProps': ['base'],
	'packages/@luke-ui/react/src/core/heading/heading-context.tsx::HeadingLevelsRenderProps': [
		'element',
		'level',
	],
	'packages/@luke-ui/react/src/core/heading/heading.tsx::HeadingProps': ['level', 'typography'],
	'packages/@luke-ui/react/src/core/icon/icon.tsx::CreateIconOptions': ['path', 'viewBox'],
	'packages/@luke-ui/react/src/core/icon/icon.tsx::CustomIconProps': ['title'],
	'packages/@luke-ui/react/src/core/icon/icon.tsx::IconProps': ['title'],
	'packages/@luke-ui/react/src/core/icon/icon.tsx::IconSpritesheetProviderProps': ['href'],
	'packages/@luke-ui/react/src/core/icon-button/icon-button.tsx::IconButtonProps': [
		'appearance',
		'icon',
		'isDisabled',
		'isPending',
		'size',
		'tone',
	],
	'packages/@luke-ui/react/src/core/kbd/kbd.tsx::KbdProps': [],
	'packages/@luke-ui/react/src/core/link/link.tsx::LinkProps': [
		'href',
		'isDisabled',
		'isStandalone',
		'tone',
	],
	'packages/@luke-ui/react/src/core/loading-skeleton/loading-skeleton.tsx::LoadingSkeletonProps': [
		'elementType',
		'isLoading',
		'radius',
	],
	'packages/@luke-ui/react/src/core/loading-skeleton/loading-skeleton.tsx::LoadingSkeletonProviderProps':
		['isLoading'],
	'packages/@luke-ui/react/src/core/loading-spinner/loading-spinner.tsx::LoadingSpinnerProps': [
		'aria-label',
		'color',
		'isLoading',
		'size',
	],
	'packages/@luke-ui/react/src/core/numeral/numeral.tsx::NumeralProps': [
		'abbreviate',
		'currency',
		'format',
		'formatOptions',
		'fontVariantNumeric',
		'precision',
		'textAlign',
		'unit',
		'value',
	],
	'packages/@luke-ui/react/src/core/primitives/button/button.tsx::ButtonProps': [
		'appearance',
		'isBlock',
		'isDisabled',
		'isPending',
		'size',
		'tone',
	],
	'packages/@luke-ui/react/src/core/primitives/checkbox/checkbox.tsx::CheckboxContentProps': [],
	'packages/@luke-ui/react/src/core/primitives/checkbox/checkbox.tsx::CheckboxControlProps': [],
	'packages/@luke-ui/react/src/core/primitives/checkbox/checkbox.tsx::CheckboxIndicatorProps': [],
	'packages/@luke-ui/react/src/core/primitives/checkbox/checkbox.tsx::CheckboxProps': ['isInvalid'],
	'packages/@luke-ui/react/src/core/primitives/combobox/clear-button.tsx::ComboboxClearButtonProps':
		[],
	'packages/@luke-ui/react/src/core/primitives/combobox/empty-state.tsx::ComboboxEmptyStateProps': [
		'children',
	],
	'packages/@luke-ui/react/src/core/primitives/combobox/input-group.tsx::ComboboxInputGroupProps': [
		'size',
	],
	'packages/@luke-ui/react/src/core/primitives/combobox/input.tsx::ComboboxInputProps': ['size'],
	'packages/@luke-ui/react/src/core/primitives/combobox/item.tsx::ComboboxItemProps': [],
	'packages/@luke-ui/react/src/core/primitives/combobox/item.tsx::ComboboxLoadMoreItemProps': [],
	'packages/@luke-ui/react/src/core/primitives/combobox/listbox.tsx::ComboboxListBoxProps': [
		'items',
		'loadMoreItem',
	],
	'packages/@luke-ui/react/src/core/primitives/combobox/popover.tsx::ComboboxPopoverProps': [],
	'packages/@luke-ui/react/src/core/primitives/combobox/root.tsx::ComboboxRootProps': [
		'aria-label',
		'defaultItems',
		'size',
	],
	'packages/@luke-ui/react/src/core/primitives/combobox/section.tsx::ComboboxSectionProps': [
		'title',
	],
	'packages/@luke-ui/react/src/core/primitives/combobox/trigger.tsx::ComboboxTriggerProps': [
		'aria-label',
		'size',
	],
	'packages/@luke-ui/react/src/core/primitives/field/description.tsx::FieldDescriptionProps': [
		'id',
	],
	'packages/@luke-ui/react/src/core/primitives/field/error.tsx::FieldErrorProps': [],
	'packages/@luke-ui/react/src/core/primitives/field/field.tsx::FieldProps': [
		'description',
		'errorMessage',
		'label',
		'necessityIndicator',
	],
	'packages/@luke-ui/react/src/core/primitives/field/label.tsx::FieldLabelProps': [
		'htmlFor',
		'necessityIndicator',
	],
	'packages/@luke-ui/react/src/core/primitives/input-group/input-group.tsx::InputGroupInputProps': [
		'aria-label',
		'className',
		'inputMode',
		'ref',
		'size',
	],
	'packages/@luke-ui/react/src/core/primitives/input-group/input-group.tsx::InputGroupPrefixProps':
		['size'],
	'packages/@luke-ui/react/src/core/primitives/input-group/input-group.tsx::InputGroupProps': [
		'className',
		'isInvalid',
		'size',
	],
	'packages/@luke-ui/react/src/core/primitives/input-group/input-group.tsx::InputGroupSuffixProps':
		['size'],
	'packages/@luke-ui/react/src/core/prose/prose.tsx::ProseProps': [],
	'packages/@luke-ui/react/src/core/quote/quote.tsx::QuoteProps': ['cite', 'lineClamp', 'textWrap'],
	'packages/@luke-ui/react/src/core/strong/strong.tsx::StrongProps': ['lineClamp', 'textWrap'],
	'packages/@luke-ui/react/src/core/text-field/text-field.tsx::TextFieldProps': [
		'aria-label',
		'errorMessage',
		'isRequired',
		'label',
		'necessityIndicator',
		'pattern',
		'placeholder',
		'prefix',
		'size',
		'suffix',
		'type',
		'validate',
	],
	'packages/@luke-ui/react/src/core/text/text.tsx::TextProps': [
		'elementType',
		'fontVariantNumeric',
		'fontWeight',
		'lineClamp',
		'shouldDisableTrim',
		'textAlign',
		'textDecoration',
		'textTransform',
		'textWrap',
		'typography',
	],
	'packages/@luke-ui/react/src/core/visually-hidden/visually-hidden.tsx::VisuallyHiddenProps': [
		'elementType',
	],
};
