/**
 * Build-time helpers that a host runs under Node to generate the playground's
 * runtime scope module and the editor's type map. Browser subpaths must not
 * import this module.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, relative, sep } from 'node:path';
import * as z from 'zod';

export type AddPlaygroundTypePackageOptions = {
	/**
	 * Replaces the package's `package.json` in the map, serialised with
	 * `JSON.stringify`. Pass a stub such as `{ exports, name }` to keep only the
	 * fields the editor's module resolution reads.
	 */
	packageJson?: unknown;
	/**
	 * Directory under `packageDir` to collect `.d.ts` files from, such as
	 * `dist`. Paths in the map stay relative to `packageDir`.
	 * @default '.'
	 */
	typesDir?: string;
};

export type PlaygroundTypeMap = {
	/** Adds every `.d.ts`, `.d.mts`, and `.d.cts` file under the package, then its `package.json`. */
	addPackage: (
		packageName: string,
		packageDir: string,
		options?: AddPlaygroundTypePackageOptions,
	) => void;
	/** Adds one file at an arbitrary virtual path, such as `file:///host/helpers.tsx`. */
	addFile: (virtualPath: string, contents: string) => void;
	/** The virtual path to contents map, in insertion order. */
	files: () => Record<string, string>;
};

/**
 * Renders the TypeScript module that maps playground import specifiers to
 * live namespace imports. Hosts write the result to their generated output path.
 *
 * Each namespace gets a positional identifier (`module0`, `module1`, …), so
 * any specifier is safe to import. Throws when a specifier appears twice.
 */
export function renderPlaygroundScopeModule(specifiers: ReadonlyArray<string>): string {
	const seen = new Set<string>();
	for (const specifier of specifiers) {
		if (seen.has(specifier)) {
			throw new Error(
				`renderPlaygroundScopeModule: duplicate specifier ${JSON.stringify(specifier)}.`,
			);
		}
		seen.add(specifier);
	}

	const importLines = specifiers.map(
		(specifier, index) => `import * as module${index} from ${JSON.stringify(specifier)};\n`,
	);
	const entryLines = specifiers.map(
		(specifier, index) => `\t${JSON.stringify(specifier)}: module${index},\n`,
	);

	return `// Generated by playground scope generation — do not edit.
${importLines.join('')}
export const playgroundScope: Record<string, unknown> = {
${entryLines.join('')}};
`;
}

/** The virtual `file:///node_modules/<packageName>/<relativePath>` path the editor resolves. */
export function playgroundVirtualPath(packageName: string, relativePath: string): string {
	return `file:///node_modules/${packageName}/${relativePath.split(sep).join('/')}`;
}

const DECLARATION_EXTENSIONS = ['.d.ts', '.d.mts', '.d.cts'];

/**
 * Collects `.d.ts`, `.d.mts`, and `.d.cts` files into a map of virtual paths
 * to contents, for a host to serialise and hand to the editor's TypeScript
 * worker.
 */
export function createPlaygroundTypeMap(): PlaygroundTypeMap {
	const files: Record<string, string> = {};

	function addPackageFile(packageName: string, packageDir: string, filePath: string): void {
		files[playgroundVirtualPath(packageName, relative(packageDir, filePath))] = readFileSync(
			filePath,
			'utf8',
		);
	}

	return {
		addFile(virtualPath, contents) {
			files[virtualPath] = contents;
		},
		addPackage(packageName, packageDir, options) {
			walkPackageFiles(join(packageDir, options?.typesDir ?? '.'), (filePath) => {
				if (!DECLARATION_EXTENSIONS.some((extension) => filePath.endsWith(extension))) return;
				addPackageFile(packageName, packageDir, filePath);
			});
			if (options?.packageJson === undefined) {
				addPackageFile(packageName, packageDir, join(packageDir, 'package.json'));
				return;
			}
			files[playgroundVirtualPath(packageName, 'package.json')] = JSON.stringify(
				options.packageJson,
			);
		},
		files: () => files,
	};
}

const packageNameSchema = z.object({ name: z.string().optional() });

/**
 * Resolves an installed package's directory from a dependent `package.json`.
 * Falls back to resolving the main entry and walking up, because some
 * packages do not export `./package.json`.
 */
export function resolvePackageDir(fromPackageJson: string, packageName: string): string {
	const require = createRequire(fromPackageJson);
	try {
		return dirname(require.resolve(`${packageName}/package.json`));
	} catch {
		let dir = dirname(require.resolve(packageName));
		while (dir !== dirname(dir)) {
			const packageJsonPath = join(dir, 'package.json');
			if (existsSync(packageJsonPath)) {
				const { name } = packageNameSchema.parse(JSON.parse(readFileSync(packageJsonPath, 'utf8')));
				if (name === packageName) return dir;
			}
			dir = dirname(dir);
		}
		throw new Error(`Could not locate package directory for ${packageName}`);
	}
}

/** Visits every file under `dir`, depth first, skipping `node_modules` directories. */
function walkPackageFiles(dir: string, visit: (filePath: string) => void): void {
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		if (entry.name === 'node_modules') continue;
		const entryPath = join(dir, entry.name);
		if (entry.isDirectory()) walkPackageFiles(entryPath, visit);
		else if (entry.isFile()) visit(entryPath);
	}
}
