name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish & deploy
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.8.0

      - name: Checkout repo
        uses: actions/checkout@main
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create release pull request or publish to npm
        uses: changesets/action@c2918239208f2162b9d27a87f491375c51592434
        with:
          version: pnpm run ci:version
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
